### ISSUE TITLE
The todo-databinding branch contains findViewById calls

### ISSUE THREAD

**Issue by curioustechizen** [googlesamples/android-architecture#103]
While most of these calls are for layout files that don't actually do any data binding in itself (i.e., for layout files that do not have the `<layout>` tag), it might be a good idea to demonstrate best practices of the data binding library and eliminate all `findViewById` calls altogether.

If the maintainers agree with this, I could submit a PR.

**Comment by JoseAlcerreca** [comment]
Thanks for the issue. Are you suggesting creating layout tags in the activities' layouts? Like in https://github.com/googlesamples/android-architecture/blob/todo-databinding/todoapp/app/src/main/res/layout/taskdetail_act.xml

It seems overkill to do that to get a ref to the fab.

**Comment by curioustechizen** [comment]
Yes that is what I was suggesting, at least in layouts where there is more than one view to find (maybe not for the fab case). I think eliminating `findViewById` calls is the "Level 0" of the data binding library.

Additionally there's looking at code like [this](https://github.com/googlesamples/android-architecture/blob/76407c5b5d48bab921b1281a43c4a5ba53d4afd1/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/addedittask/AddEditTaskFragment.java#L91) where you already have an instance of ViewDataBinding. You don't need the `findViewById` calls there. `mTitle` and `mDescription` can be replaced with `mViewDataBinding.addTaskTitle` and `mViewDataBinding.addTaskDescription` respectively.

**Comment by JoseAlcerreca** [comment]
I don't see the data binding lib as a way to eliminate findViewById everywhere (there's butterknife for that), so I would only use it for actual data binding.

I agree on the second part. A PR would be very much appreciated!
