### ISSUE TITLE
@NonNull annotation and checkNotNull() used incorrectly

### ISSUE THREAD

**Issue by samiuelson** [googlesamples/android-architecture#110]
I noticed very incorrect usage of `checkNotNull()` guava method for objects with `@NonNull` annotations. 
Example from TasksPresenter class:

```
@Override
    public void openTaskDetails(@NonNull Task requestedTask) {
        checkNotNull(requestedTask, "requestedTask cannot be null!");
        mTasksView.showTaskDetailsUi(requestedTask.getId());
    }

    @Override
    public void completeTask(@NonNull Task completedTask) {
        checkNotNull(completedTask, "completedTask cannot be null!");
        mTasksRepository.completeTask(completedTask);
        mTasksView.showTaskMarkedComplete();
        loadTasks(false, false);
    }

    @Override
    public void activateTask(@NonNull Task activeTask) {
        checkNotNull(activeTask, "activeTask cannot be null!");
        mTasksRepository.activateTask(activeTask);
        mTasksView.showTaskMarkedActive();
        loadTasks(false, false);
    }
```
Guys, read the docs please. `@NonNull` is used to assure that related object is never ever null. The `checkNotNull()` is used incorrectly therefore. `checkNotNull()` could be called on particular object before passing it with some of these methods above, by method call.
It's only one example. Such type of mistake is common among whole project. It's not a bug but it's very misleading and ugly.

**Comment by Rainer-Lang** [comment]
Do you want to make a pr?

**Comment by samiuelson** [comment]
Yes, I can fix it.

**Comment by JoseAlcerreca** [comment]
As agreed in #113 , closing!
