### ISSUE TITLE
MVP Rx java confusing

### ISSUE THREAD

**Issue by harisvsulaiman** [googlesamples/android-architecture#114]
I have had some problems. With sample.
1. Is the activity supposed to be a simple container for fragment(controller with no view attached)? It doesn't seem so from the sample (toolbar in activity).
2. Can/should the presenter methods be called in activity.
3. The presenter should only contain view related logic? (Routing / service launche etcnot be there?)
3. Finally can I mix and match(fragment as view and activity as view).

**Comment by JoseAlcerreca** [comment]
The Rx java sample is in development.

**Comment by harisvsulaiman** [comment]
@JoseAlcerreca i have edited the title to better describe my frustration, i think those points are valid for all mvp samples.
It was just that I was using Rx.

So I thought we make a new architecture specifically for android .(not being overconfident) #115
