### ISSUE TITLE
New architecture specific for android .

### ISSUE THREAD

**Issue by harisvsulaiman** [googlesamples/android-architecture#115]
Should we follow architecture patterns which are foreign. To android and apply it ?
I think the better solution is to create a new architecture pattern taking into account, 
1. The android api
2. Vast amount of main stream libraries.
3.leverage databinding . Api available in android sdk

**Comment by JoseAlcerreca** [comment]
They all take the Android API into account, and we deal with 2) and 3) in the pertinent samples.
