### ISSUE TITLE
Why not use a sample Activity but a Activity with single Fragment

### ISSUE THREAD

**Issue by doulala1986** [googlesamples/android-architecture#116]
Hi,I am comfused when I read the code .

**Why not use a sample Activity but a Activity with single Fragment？**

 Is this design a better Practice?

Thanks a lot!

**Comment by shriduttkothari** [comment]
Yes, using fragments are recommended as a best practice, because fragments are reusable, lightweight and moduler.

**Comment by doulala1986** [comment]
thanks very much~~it‘s very useful for me！

**Comment by doulala1986** [comment]
if only a simple ui and function，I should write more one fragment.java and more one /layout/activity.xml

**Comment by viniciussoares** [comment]
I also think in this case the fragment is unnecessary, it just add more code and complexity.

**Comment by JoseAlcerreca** [comment]
It does add more code and complexity, yes. Here is our reasoning: https://github.com/googlesamples/android-architecture/tree/todo-mvp/

But we added an external fragmentless sample in case you're sure you don't want to use Fragments.
