### ISSUE TITLE
rxjava brash,crash

### ISSUE THREAD

**Issue by Guolei1130** [googlesamples/android-architecture#129]
when i change ‘supportLibraryVersion’ to '23.2.0',tha app will crash,i think the xml has error.
in tasks_act.xml and addtask_act.xml,
```
app:layout_anchor="@id/coordinatorLayout"
```
Should be modified to
```
app:layout_anchor="@id/contentFrame"
```

**Comment by JoseAlcerreca** [comment]
rxjava is still in development.
