### ISSUE TITLE
When to use Intent for data to activity and when load from repository?

### ISSUE THREAD

**Issue by Rainer-Lang** [googlesamples/android-architecture#133]
This is a general question.

In these blueprints the Intent is used to pass the TaskId from TasksActivity to eg TaskDetailActivity/Fragment.
Then the data of this task is loaded and shown.

My question is: If I have all data in the list (here TasksActivity/TasksFragment) - should I put this data in an Intent or should the DetailFragment load the data from repository?

For my understanding, if all data is already loaded and "fresh" I should use Intent. 
If I don't have all data or data is outdated then load all from repository.

UPDATE:
The TaskId is passed to Fragment.newInstance AND even to the presenter. Why?

**Comment by fisache** [comment]
I think it's just for general.
make following linke reference.
http://stackoverflow.com/questions/25194102/is-it-more-efficient-to-pass-large-parcelable-or-pass-id-and-query-db

parcelable data is limited to 1MB, so if you intent bitmap over 1MB, it's better to use task id and obtain task from repository.

**Comment by Rainer-Lang** [comment]
@fisache thanks for the answer. This helps a lot.
