### ISSUE TITLE
volley code is belong to presenter or model ?

### ISSUE THREAD

**Issue by yipinghuo** [googlesamples/android-architecture#136]
i uesed  volley library for server request data in my app，and in this method Application.context is used。Now i do not know whether this part code is belong to presenter or model ?

      /**
         *d登录
         *
     * @param corpCode      公司名
     * @param userName      用户名
     * @param password      密码
     * @param loginListener 回调监听
     * @throws IOException
     * @throws AuthFailureError
     */
    public void login(@NonNull String corpCode, @NonNull final String userName, @NonNull String password, final VolleyLoaderListener loginListener) throws IOException, AuthFailureError {
        // 构造访问路径
        String url = ServiceEndPoint.LoginUri(corpCode, userName, password);
        // 发送请求
        JsonObjectRequest request = new JsonObjectRequest(Request.Method.POST, url, null,
                new Response.Listener<JSONObject>() {
                    @Override
                    public void onResponse(JSONObject response) {
                        try {
                            loginListener.loadSucceed(response);
                        } catch (JSONException e) {
                            e.printStackTrace();
                        }

                    }
                }, new LoginErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                super.onErrorResponse(error);
                loginListener.loadFailed();
            }
        }
        );
        VolleySingleton.getInstance(HksApplication.mContext).addToRequestQueue(request);
    }

**Comment by JoseAlcerreca** [comment]
Hey yipinghuo,

Since this is not a sample issue I have to close it to keep the list clean, so please post these questions on StackOverflow or similar.

That code doesn't belong in the presenter or model, but should be called from the presenter. Check out the Injection class, it's a good place to provide a singleton.
