### ISSUE TITLE
Adding functions/behaviours in repository

### ISSUE THREAD

**Issue by jchesterisidoro** [googlesamples/android-architecture#142]
I'm confused about the best way to add more functions in repository such as 
1.) "checking for model/model property uniqueness", and
2.) "model property validity".
I'm not sure if this should be put on the repository or model or presenter.

Any ideas? Thanks.

**Comment by gokhanbarisaker** [comment]
Is it possible for you to provide samples? e.g., the source code or article that made you ask this question.

**Comment by JoseAlcerreca** [comment]
Closing this one, feel free to reopen.

**Comment by jchesterisidoro** [comment]
In number 1.) let's say that we need the Task object to be unique. No Task should have a similar title and content. Should I check that in the repository? Or in the Task object itself? Presenter? Domain?
As for 2.) what if we need the Task title to have a number of characters required, where should I put that?
