### ISSUE TITLE
todo-mvp-dagger: Why are the presenters injected into activities, but never used?

### ISSUE THREAD

**Issue by Rainer-Lang** [googlesamples/android-architecture#145]
I'm just wondering why it is done.

like here:
https://github.com/googlesamples/android-architecture/blob/todo-mvp-dagger/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/addedittask/AddEditTaskActivity.java#L40

**Comment by mladenrakonjac** [comment]
It is not a big thing. In every view you have to inject the correspond presenter. Currently, it is not used, but maybe it will need to be used when you implement some new feature

**Comment by Rainer-Lang** [comment]
So it's for possible future usage.
Thanks.

**Comment by n0m0r3pa1n** [comment]
No, they inject it so the corresponding setPresenter method on the view can be called when they pass the fragment to Dagger on line 77. Do you see they inject the concrete implementation, not the interface from the contract? I asked the same question here: https://github.com/googlesamples/android-architecture/issues/139
