### ISSUE TITLE
New sample: MVVM + RxJava

### ISSUE THREAD

**Issue by johnfrey99** [googlesamples/android-architecture#156]
It seems within the android community MVVM is gaining popularity over MVP particularly with the aid of RxJava. Has there been any consideration of a MVVM + RxJava example?

[Better Android software development: MVVM with RxJava](https://www.codevate.com/blog/13-better-android-software-development-mvvm-with-rxjava?utm_source=androiddevdigest)

[MVVM and RxJava – the perfect mix](http://www.slideshare.net/FlorinaMuntenescu/mvvm-and-rxjava-the-perfect-mix-61526418?utm_source=Android+Weekly&utm_campaign=d49acf65be-Android_Weekly_204&utm_medium=email&utm_term=0_4eb677ad19-d49acf65be-337299993)

[Use Mosby for the MVP](https://github.com/artem-zinnatullin/qualitymatters/issues/175)

[RxJava: Android MVVM App structure with Retrofit](https://medium.com/@manuelvicnt/rxjava-android-mvvm-app-structure-with-retrofit-a5605fa32c00#.rbhzrxwy4)

https://github.com/viethoa/android-mvvm-rxjava-demo

**Comment by JoseAlcerreca** [comment]
Yes there's an issue. #138
