### ISSUE TITLE
[todo-mvp-clean] should the data layer be synchronous instead?

### ISSUE THREAD

**Issue by soapsign** [googlesamples/android-architecture#157]
Most of the time the goal of asynchronous task is to avoid blocking the main thread. In domain layer, usecases are already in asynchronous mode. So I don't think the data layer still need to use asynchronous mode. If we do the data access in synchronous mode, we can avoid additional thread switch and the complexity of callback.

**Comment by flipper83** [comment]
HI @soapsign , this is explained in the readme. We keep the data layer async only for keep similar to the base project and make easier compare different options. As you said have a sync repositories is a really good solution, that I recommend you try in your project.

**Comment by soapsign** [comment]
Thanks! I should read the readme before diving into the code.
