### ISSUE TITLE
Poor rxjava usage

### ISSUE THREAD

**Issue by alexander-shustanov** [googlesamples/android-architecture#160]
I don't see any benefits of using rxjava in your rxjava sample.  Firstly, it works in single thread - what if reading the database will be very long, or editing the tasks affects some other parts of model and modifying ones takes a lot of time? Secondly, to be reactive means we react on the data. But the example designed like it REQUESTS the data, despite it use rxjava for it. It should subscribe the data.
What about to isolate data in separate scheduler, for example in `HandlerScheduler.from(.../*handler from some HandlerThread*/)`?

Also, Repositories should store BehaviorSubjects with tasks list and Presenters subscribe them at onResume and unsubscribe at onPause. All tasks changes will push to subject and presenters will react on every (or we can use sample, throttleLast, debounce etc) change.

**Comment by ErikHellman** [comment]
What do you mean with "it works in single thread"? We're performing the request towards the repositories on the IO scheduler, which will use a new thread if none is available. 

I also don't see the purpose of using a subject in the repository. It might make sense to use `.share()` to provide a cache using Rx, but we decided to keep things simple for now. 

On the comment that this is not a reactive example I can somewhat agree. However, the sample is about using the RxJava framework to fetch the data from the repository. Future samples might use an even more event-driven approach, which would basically be an MVVM sample, but we haven't completed that yet.

**Comment by djodjoni** [comment]
On the point of `Subject` and `.share() ` i believe sharing is not the best option when 
1) we need to get Observable source before it is actually there.
2) the Observable source is not stable as in the current repositories we manufacture a new observable when we fetch a task or a list, it would be quite difficult to share that
btw I would use Relays and stream errors that may happen separately.

However I agree with @ErikHellman to keep this example simple (without Subjects/Relays) nor share and demonstrate mostly the functional part of RxJava.

Btw I plan to do an external example using [RxHub](https://github.com/apptik/rxHub) which will be basically more data/action event driven and decouple components even more.
I'd love to get some thoughts on that :)

**Comment by JoseAlcerreca** [comment]
@djodjoni awesome, feel free to start a new issue to track that one. Thanks!

**Comment by JoseAlcerreca** [comment]
Closing this now, I think the questions were answered.
