### ISSUE TITLE
[todo-mvp-*] mTaskId checks and inconsistency

### ISSUE THREAD

**Issue by djodjoni** [googlesamples/android-architecture#161]
mTaskId is used in both AddEditTaskPresenter and TaskDetailPresenter

in AddEditTaskPresenter when null it means it is new and we throw, when action that does not apply to this state is executed.
in TaskDetailPresenter however the situation is different and we don't have this 'new task' concept where we accept null value for mTaskId however in the code we allow it. What more is that we also catching this behavior with (null == mTaskId || mTaskId.isEmpty()) and display "missing task message" which IMO is incorrect. Another strange thing is that we do this check for all operations except "deleteTask".

Is there a reason for this?
In case it is a but I propose:
in TaskDetailPresenter:
-  @Nullable private String taskId -> @NonNull private final String taskId;
- we throw when (null == mTaskId || mTaskId.isEmpty()) fails

**Comment by JoseAlcerreca** [comment]
Yeah we could throw but we decided to show an error message.

Not a big deal, since it's an architecture sample.
