### ISSUE TITLE
how to uses MVP-RxJava architecture in viewpager ?

### ISSUE THREAD

**Issue by ThinWonton** [googlesamples/android-architecture#169]
firstly, thanks to solved the problem of communicate between two presenter. 

But there is a serious need to solve how to uses viewpager in mvp architecture. In fact, fragment is more suitable to role in 'View'  than Activity which usually used to control fragment. The viewpager, you know, is often used in our apps.

**Comment by Rainer-Lang** [comment]
+1

**Comment by JoseAlcerreca** [comment]
Are you referring to the tablet presenter branch?

**Comment by savepopulation** [comment]
I've tried different implementations about this problem. I think the most suitable one is passing fragments to ViewPager adapter and before pass check if there's a fragment which reained by ViewPager. If there's use it as View and pass it to ViewPager's adapter.

You can find the fragments you used in ViewPager by Tag with this pattern:

**"android:switcher:"+R.id.your_view_pager+":"+position**

Here i'll send an example code.

`BankRollDetailFragment detailFragment = (BankRollDetailFragment) getSupportFragmentManager()
                .findFragmentByTag(UiUtil.generateViewPagerFragmentTag(R.id.viewpager_bankroll, BankRollTabsAdapter.TAB_DETAIL));
        if (detailFragment == null) {
            detailFragment = BankRollDetailFragment.newInstance();
        }

        BankRollBetsFragment betsFragment = (BankRollBetsFragment) getSupportFragmentManager()
                .findFragmentByTag(UiUtil.generateViewPagerFragmentTag(R.id.viewpager_bankroll, BankRollTabsAdapter.TAB_BETS));
        if (betsFragment == null) {
            betsFragment = BankRollBetsFragment.newInstance();
        }

        final SparseArray<Fragment> fragments = new SparseArray<>();
        fragments.put(0, detailFragment);
        fragments.put(1, betsFragment);

        final ViewPager viewPagerBankRollTabs = (ViewPager) findViewById(R.id.viewpager_bankroll);
        final TabLayout tabLayout = (TabLayout) findViewById(R.id.tabs);
        final BankRollTabsAdapter bankRollTabsAdapter = new BankRollTabsAdapter(getSupportFragmentManager(),
                getResources().getStringArray(R.array.tabs_bankroll),
                fragments);
        viewPagerBankRollTabs.setAdapter(bankRollTabsAdapter);
        tabLayout.setupWithViewPager(viewPagerBankRollTabs);

        DaggerBankRollComponent.builder()
                .bankRollDetailPresenterModule(new BankRollDetailPresenterModule(detailFragment, bankrollId))
                .bankRollBetsPresenterModule(new BankRollBetsPresenterModule(betsFragment))
                .bankRollRepositoryComponent(((BetSafeApp) getApplication()).getBankRollRepositoryComponent())
                .build()
                .inject(this);`
