### ISSUE TITLE
[all] Question: Parametric Interface for TasksDataSource

### ISSUE THREAD

**Issue by JakeLoo** [googlesamples/android-architecture#170]
When creating a repository, the constructor takes two parameters which are both `TasksDataSource` specifically one for remote data source and another for local data source. 
One potential issue is that TasksDataSource that is created meant to be used for local, can interchangeably be used as remote data source. 

Should the TasksDataSource be a parametric interface that holds the type of data source (i.e: local, remote)? 
Definitely, it may seem unnecessary and a lot of extra codes that need to be written, but it could also reduce the risk of misplacing local data source as remote data source, vice versa.

The changes would look like:
```
public interface TasksDataSource<T extends DataSourceType> {
```

```
public class TasksLocalDataSource implements TasksDataSource<DataSourceLocal> {
public class TasksRemoteDataSource implements TasksDataSource<DataSourceRemote> {
```

```
private final TasksDataSource<DataSourceRemote> mTasksRemoteDataSource;
private final TasksDataSource<DataSourceLocal> mTasksLocalDataSource;

public static TasksRepository getInstance(
TasksDataSource<DataSourceRemote> tasksRemoteDataSource, 
TasksDataSource<DataSourceLocal> tasksLocalDataSource) {
```

**Question**: Is it worth it?

**Comment by JoseAlcerreca** [comment]
That's a bit convoluted, I think. If you want to make sure users of the repository don't mix up the data sources, you can use the concrete classes instead of the interfaces in the constructor. Using interfaces was probably excessive future-proofing.
