### ISSUE TITLE
[todo-mvp-rxjava] Add/Edit view knows too much

### ISSUE THREAD

**Issue by JoseAlcerreca** [googlesamples/android-architecture#171]
https://github.com/googlesamples/android-architecture/blob/todo-mvp-rxjava/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/addedittask/AddEditTaskFragment.java#L87

We moved this logic to the presenter in the rest of the branches.

**Comment by florina-muntenescu** [comment]
PR here: https://github.com/googlesamples/android-architecture/pull/172
