### ISSUE TITLE
Architecture selection factors guide - all

### ISSUE THREAD

**Issue by geniushkg** [googlesamples/android-architecture#175]
-  There must be some use case where MVP architecture suits best , while in another use case MVC or redux-flux or MVVM suites best.

-  Currently, most android google dev's suggest MVP as standard , I think there should be minimal documentation on which architecture to choose and when to choose

- Rx is hot and trending but , we all know that :  **premature optimization is the root of all evil** , selecting some technology in tech stack because its hot trending is not the correct way. There must be some document which helps engineers draw lines between implementation and doesn't make things complicated.
- Please let me know your thoughts , I am planning to make simple web based tool which will help developers to choose architechture accordingly.

**Comment by JoseAlcerreca** [comment]
We have a simple comparison table here 
https://github.com/googlesamples/android-architecture/wiki/Samples-at-a-glance

But it's hard to draw hard lines between architectures. 

The project looks interesting, let us know when you're done!

Closing this now, as it's not an issue with samples.
