### ISSUE TITLE
[todo-mvp-clean] Separate layers by modules.

### ISSUE THREAD

**Issue by filipedelimabrito** [googlesamples/android-architecture#176]
Why not separate the layers (domain and data) by module?

**Comment by Rainer-Lang** [comment]
Why? :)
What reasons do you have in mind?

**Comment by filipedelimabrito** [comment]
See this [well done project] (https://github.com/android10/Android-CleanArchitecture) and you will have an idea about!
The structure is more organized IMO...

**Comment by Rainer-Lang** [comment]
Then you know [this](https://github.com/android10/Android-CleanArchitecture/pull/103) and the discussions around.

**Comment by malmstein** [comment]
@filipedelimabrito what are the benefits of doing this?

**Comment by Rainer-Lang** [comment]
Could this be closed?

**Comment by JoseAlcerreca** [comment]
Yes, thanks for your help maintaining this tracker Rainer-Lang!

**Comment by filipedelimabrito** [comment]
Sorry about writing only now. 

If anyone is insterested yet, the benefit is: [Separation of concerns.](https://en.wikipedia.org/wiki/Separation_of_concerns)

You can check this [paper](https://www.cs.utexas.edu/users/EWD/ewd04xx/EWD447.PDF) from Dijkstra and a great [reading](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-170-software-studio-spring-2013/lecture-notes/MIT6_170S13_08-sep-of-conc.pdf) from Daniel Jackson (MIT) to know why.
