### ISSUE TITLE
all-Repository with many models

### ISSUE THREAD

**Issue by pj-admin** [googlesamples/android-architecture#180]
In all projects, there is only one Model - Task, but we have more models in real project. 
The problem is DataSource, Repository and local, remote are served for only Task model. What if we have more models and they have relationship together ? How to implement them ? Anyone has examples ?

Sorry for dumb question, I am newbie.
Thank you for reading.

**Comment by JoseAlcerreca** [comment]
Hi,

In order to keep this tracker clean, please use it only for sample issues, not general questions. A G+ community or maybe stackoverflow will probably yield better results.
