### ISSUE TITLE
[todo-mvp-rxjava] EspressoIdlingResource never decremented after work

### ISSUE THREAD

**Issue by AnirudhaAgashe** [googlesamples/android-architecture#186]
In [todo-mvp-rxjava] EspressoIdlingResources is incremented in StatisticsPresenter and TasksPresenter in method loadStatistics and loadTasks respectively. But the EspressoIdlingResources is never decremented upon completion of work.

**Comment by JoseAlcerreca** [comment]
This sounds strange. If true then IRs are not being used or registered, otherwise Espresso would just wait indefinitely.  @florina-muntenescu, @ErikHellman can you have a look?

**Comment by florina-muntenescu** [comment]
PR created [here](https://github.com/googlesamples/android-architecture/pull/222)

**Comment by florina-muntenescu** [comment]
fix merged.
