### ISSUE TITLE
Wrong constant name

### ISSUE THREAD

**Issue by huzhenjie** [googlesamples/android-architecture#187]
Wrong constant name in
`android-architecture/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/data/source/local/TasksDbHelper.java`

```
public class TasksDbHelper extends SQLiteOpenHelper {

    //...

    private static final String BOOLEAN_TYPE = " INTEGER";

    //...
```

**Comment by gregpearce** [comment]
There is no boolean type in SQLite and you store booleans in Integer columns as 0 or 1.
