### ISSUE TITLE
Sample using Conductor and a single Activity architecture

### ISSUE THREAD

**Issue by gregpearce** [googlesamples/android-architecture#192]
Hi everyone,

I decided to try making a sample that only uses a single Activity architecture using the [Conductor library](https://github.com/bluelinelabs/Conductor).

[I've put the branch up here](https://github.com/gregpearce/android-architecture/tree/todo-mvp-conductor) and I'd really appreciate any feedback!

It turned out to not be too difficult, the Activities and Fragments became Controllers and everything else stayed the same. I had to do some interesting code around getting the DrawerLayout working and constantly changing the ActionBar to have new stuff in it. 

The main thing left to do is that it broke a few of the Espresso tests and also made most of them super flakey. 
The problem is that the test no longer knows that it needs to wait while the next Controller loads (I guess Espresso is usually aware of Activity transitions and I no longer have that crutch).  I had a look at using `IdlingResource` to solve this, but I'm not experienced with Conductor or Espresso, I'll keep working on it.
Also, the hermetic UI tests of individual Activities will probably never work hermetically since I don't think I can jump into a specific Controller like you can with Activities, you need to navigate there.

**Comment by JoseAlcerreca** [comment]
Hey Greg,

I've labelled this as request, although it's not actually a request, since you already finished it.

It's a great example of what we wanted the community to do with this project! 

Before adding it to the list of external samples I'd ask you to:
 - Solve UI tests
 - Explain in the README what the library does and what design decisions you made

I don't think you need Idling Resources for that, unless you're doing things outside of the main thread.

**Comment by gregpearce** [comment]
Cool ok! I'll try to find some time soon to finish it off and polish it a little / add more documentation.

**Comment by gregpearce** [comment]
Hi Jose,
I managed to spend some time on it today. 

The Espresso tests are all working now, mostly through small refactorings in the Espresso methods that were being called and by turning off the animations on the device I was using for the testing. The only weird thing I had to do in the end was use the `IdlingResource` to track whether the Navigation Drawer had finished animating open/closed (explained in the README).

I also polished the code a bit more and updated the README to explain how the architecture works. 

[It's all been pushed to this branch.](https://github.com/gregpearce/android-architecture/tree/todo-mvp-conductor)

Let me know if you have any feedback!

**Comment by JoseAlcerreca** [comment]
Hey greg, looks good!

Have you used cloc to take the LOC?

**Comment by gregpearce** [comment]
Yep, it's in the README

**Comment by JoseAlcerreca** [comment]
Cool, adding it to the list!

**Comment by JoseAlcerreca** [comment]
Done! Thanks Greg!
https://github.com/googlesamples/android-architecture/blob/master/README.md

**Comment by gregpearce** [comment]
Great! Thanks Jose!
