### ISSUE TITLE
Turkish locale issue in testLogging events

### ISSUE THREAD

**Issue by figengungor** [googlesamples/android-architecture#208]
![error](https://cloud.githubusercontent.com/assets/3411015/19215328/9a13a570-8da3-11e6-9a0b-50e7bda71377.png)

**Comment by JoseAlcerreca** [comment]
Thanks for the report and PR. Apparently there's a problem with Turkish and Gradle in the conversion from enums to strings, nothing to do with the sample or the Android plugin. Closing this.
