### ISSUE TITLE
[all] adding CircleCI configuration file

### ISSUE THREAD

**Issue by oldergod** [googlesamples/android-architecture#209]
At the moment there is only `TravisCI` configuration file. Adding those for `CircleCI` would be fairly easy to do and Jose said it could be a nice addition to the project.
I am willing to do it if welcomed. In the case I need to merge on all projects, do I need to create a PR for each or one would be enough for the merge-master to pass it on the others?

**Comment by JoseAlcerreca** [comment]
todo-mvp is enough. It'll get merged at some point. 

Thanks for volunteering! However I don't think it's a good idea to have both at the same time building and unit testing. I guess we can enable one and disable the other for tests. Any idea?

**Comment by oldergod** [comment]
We could just add those `circle.yml` without actually linking the project to circle.com?

**Comment by JoseAlcerreca** [comment]
Since we know the Travis CI config works, I would disable Travis and try out circle for now, with just build and unit test. When we have Firebase Test Lab we'll add UI tests.

(Where you at the Devfest in Tokyo last Sunday?)

**Comment by oldergod** [comment]
I'll add the `circle.yml` soon then, thank you.

(yes)

**Comment by TwitRco** [comment]
Seems legit to at least give a try and Tested y Firebase

(7th November we're at Berlin's Devfest ,happy for meetup dudes!)

**Comment by oldergod** [comment]
I'll be happy to set up Firebase Test Lab as well when possible.

**Comment by JoseAlcerreca** [comment]
@oldergod I've got the service account ready. Please comment on #229 if you have any experience with that.

**Comment by oldergod** [comment]
In all honesty, I have yet to play with Firebase Test Lab. It is something I will study anyway at work this month so I will have plenty of time to improve the process up to a satisfactory level.

**Comment by JoseAlcerreca** [comment]
Continued in https://github.com/googlesamples/android-architecture/pull/230
