### ISSUE TITLE
setPresenter() on Fragments considered harmful?

### ISSUE THREAD

**Issue by joshallenit** [googlesamples/android-architecture#212]
The setPresenter() methods on your fragments are violating the setArguments() pattern on fragments that is used to preserve arguments when the fragment is recreated. It looks like there is an architectural problem. You should instead have the Activity or parent Fragment implement an interface that returns the presenter.

https://github.com/googlesamples/android-architecture/blob/todo-mvp/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/statistics/StatisticsFragment.java

See https://developer.android.com/training/basics/fragments/communicating.html and http://stackoverflow.com/a/14930903/1596587

**Comment by JoseAlcerreca** [comment]
What is the specific architectural problem?

The Fragments framework has a lot of features that make your life easier, but you need to know about them (setRetainInstance is a good example of this). In this particular sample we're taking a more manual approach, handling state and config changes.

**Comment by JoseAlcerreca** [comment]
Closing for now, feel free to reopen.
