### ISSUE TITLE
Samples in own folders instead branches

### ISSUE THREAD

**Issue by alexsimo** [googlesamples/android-architecture#213]
Think it would be better putting the samples into separate and own folders instead branches.

The only pro can find for using branches is easier for the PR.

**Comment by Rainer-Lang** [comment]
Yes, the branches are a mess, especially if you want to work with more than one branch.

**Comment by JoseAlcerreca** [comment]
Branches make the maintenance possible. Do more people feel this way? The initial idea was to have the branches as development branches and make "releases" by pushing all changes to master.

**Comment by alexsimo** [comment]
I like the initial idea @JoseAlcerreca. But more people should also say their opinion.

**Comment by ewoks** [comment]
Original idea is good and I am fine with branches

**Comment by ravidsrk** [comment]
I created yeomon generator to create android using these architecture, separate branches helped me in many ways. https://github.com/ravidsrk/generator-android-architecture

**Comment by ItisSoham** [comment]
I would go with Folders. Just for the ease of use.

**Comment by JoseAlcerreca** [comment]
Thanks for the feedback, we'll consider it!
