### ISSUE TITLE
[todo-mvp] Bug: EditTask doesn't save state on a configuration change

### ISSUE THREAD

**Issue by passsy** [googlesamples/android-architecture#217]
When editing a task (changing the title), the changes do not survive a configuration change.

Reason: `start()` is called from the Fragments `#onResume()`. This triggers `populateTask()` resetting the UI to the state of the loaded task from the repository. The Presenter isn't aware of changes of the TextViews in the Fragment.

This happens in two cases:
- configuration change
- bring Activity to foreground `#onResume()`

Here is a test highlighting this problem. It works but needs some adjustments

``` java
    @Test
    public void configurationChange_retainsState() throws Throwable {

        // TOOD check for correct context. targetContext isn't correct
        final TasksRepository tasksRepository = Injection
                .provideTasksRepository(InstrumentationRegistry.getTargetContext());
        final String taskId = "0001";
        final Task task = new Task("Title", "description", taskId);
        tasksRepository.saveTask(task);

        // TODO is there a nicer way to start a activity with a IntentsTestRule and Intent arguments
        final Intent intent = new Intent(InstrumentationRegistry.getTargetContext(),
                AddEditTaskActivity.class);
        intent.putExtra(AddEditTaskFragment.ARGUMENT_EDIT_TASK_ID, "0001");
        mAddTaskIntentsTestRule.launchActivity(intent);

        onView(withId(R.id.add_task_title)).check(matches(withText("Title")));
        onView(withId(R.id.add_task_description)).check(matches(withText("description")));

        onView(withId(R.id.add_task_title)).perform(replaceText("Foo"));
        onView(withId(R.id.add_task_description)).perform(replaceText("Bar"));

        mAddTaskIntentsTestRule.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                // TODO handle recreate for API 10
                mAddTaskIntentsTestRule.getActivity().recreate();
            }
        });

        onView(withId(R.id.add_task_title)).check(matches(withText("Foo")));
        onView(withId(R.id.add_task_description)).check(matches(withText("Bar")));
    }
```

**Comment by savepopulation** [comment]
I think all samples (exclude loader implementation because loaders can survive orientation change) cannot survive orientation change. For example when you rotate the phone while getting tasks, app re send same request in mvp clean architecture and rxjava sample. If i'm wrong please correct me.

**Comment by passsy** [comment]
IMHO handling a configuration change should be the minimal requirement for any sample implementations which claim to be better than putting all code into an Activity. 
On one hand it would be nice if requests wouldn't be sent twice but resending GET requests doesn't cause problems. On the other hand a bug like this is a problem because the input of a user is lost after a rotation.

The reason why I care so much about configuration changes is that I'm working on a [fork](https://github.com/passsy/thirtyinch-sample) of this project using a MVP library which eliminates state loss by architecture. The required code is usually shorter than other mvp implementations although it requires some glue code between view and presenter. But when I'm comparing it to the current implementation it's longer because the rotation is simply not handled in the base project.

**Comment by JoseAlcerreca** [comment]
Interesting, can you create a new issue to track that development? I'll close this one.
