### ISSUE TITLE
Remove Guava as a dependency

### ISSUE THREAD

**Issue by AfzalivE** [googlesamples/android-architecture#22]
Absolutely no need to import 14k methods just to do ```checkNotNull()```, ```checkArguments()```, ```Lists.newArrayList()```, ```Objects.equal()```, and ```Objects.hashCode()```

https://gist.github.com/AfzalivE/6c813c770aea498610f235001ee065ef

I can submit a PR if needed.

In addition to this, maybe there should be a method count column in the readme code metrics.

Method count went from 34398 to 19808.

**Comment by JoseAlcerreca** [comment]
Added #23 and #24. Copying methods from library to a utils class is not a practice we want to encourage. I'll leave this open for now to collect opinions.

**Comment by malmstein** [comment]
That's a valid point @AfzalivE. However I'd rather use a trimmed version of Guava using ProGuard, see https://github.com/googlesamples/android-architecture/issues/24
