### ISSUE TITLE
Best sample: Containing Dagger + RXJava + Retrofit + Sqlbrite + data binding + clean pattern

### ISSUE THREAD

**Issue by AlirezaAkbarix** [googlesamples/android-architecture#221]
Of course all separated samples are OK and using each of them is easy, but we need a complete sample that contains almost all thing that google believes them too (maybe they can be `Dagger`, `RXJava`, `Retrofit`, `Sqlbrite`,  `data binding`, `clean pattern` and etc) we need to have a **complete reliable** sample that can be used in the real world!

**Comment by JoseAlcerreca** [comment]
Thanks. If someone wants to write it we'll add it to external contributors. For now on I'm closing this one because there are similar ones already.
