### ISSUE TITLE
Add demo of testing with Page Object Pattern and Espresso

### ISSUE THREAD

**Issue by sebaslogen** [googlesamples/android-architecture#225]
Basic examples are good but large test suites need architecture and order to prosper.
A very good pattern is to organize test code and make it reflect the actual user interface with the Page Object Pattern. In a nutshell, the tests contain objects with API to interact and test each view, so test scenarios become independent of testing details like wich button id is pressed to login.
The pattern is explained in these links and examples:
- http://martinfowler.com/bliki/PageObject.html
- http://docs.seleniumhq.org/docs/06_test_design_considerations.jsp#page-object-design-pattern
- https://medium.com/@sebaslogen/the-evolution-journey-of-android-gui-testing-f65005f7ced8
- https://realm.io/news/kau-jake-wharton-testing-robots/

**Comment by JoseAlcerreca** [comment]
Thanks. This being a set of architecture samples I think we can live without it for now, no need to force the pattern.

**Comment by jerimiah797** [comment]
Lame. PageObject is an architecure.
