### ISSUE TITLE
All branches: run UI tests on Firebase Test Lab with Travis

### ISSUE THREAD

**Issue by JoseAlcerreca** [googlesamples/android-architecture#229]
There's a way to add the client secrets to travis, encrypting a file:

http://engineering.dailymotion.com/running-firebase-test-lab-on-travis-ci/

But I'm not sure about this particular implementation. `after_success` looks like the wrong hook to run UI tests unless we just want to warn about failures. Not sure how that'd work.

**Comment by oldergod** [comment]
As you said, I don't think `after_success` is the right one to run those tests.
I would rather run them as a simple extra step in the `script` list of commands and then use `after_success` or `after_script` to download the results via `gsutil`.

**Comment by JoseAlcerreca** [comment]
Apparently Travis is having problems at the moment. The CLI tool doesn't authenticate
https://github.com/travis-ci/travis.rb/issues/448 and others
