### ISSUE TITLE
Add method count to READMEs

### ISSUE THREAD

**Issue by JoseAlcerreca** [googlesamples/android-architecture#23]
Pre and post-minifying.

**Comment by fcduarte** [comment]
It's really cool the new Built-in shrinker .. It'd be nice to showcase how it reduces big libraries like Guava on debug builds.

**Comment by fcduarte** [comment]
One suggestion is to add the dexcount plugin: https://github.com/KeepSafe/dexcount-gradle-plugin

**Comment by JoseAlcerreca** [comment]
Method count in 
https://github.com/googlesamples/android-architecture/wiki/Samples-at-a-glance
