### ISSUE TITLE
[todo-mvp-clean] One view, Multiple presenters

### ISSUE THREAD

**Issue by 13kz** [googlesamples/android-architecture#243]
I have a complex view and I'd like to add a multiple presenters for the same View. 
I know that generally there is a one to one mapping between View and Presenter. But one of the most difference between MVC and MVP is the possibility to use multiple presenters for a complex View.

**So using this architecture, is there a way to handle this?**

**Comment by FarajiMehrdad** [comment]
Best way is  use UseCases in one presenter

**Comment by JoseAlcerreca** [comment]
Check out the tablet variant, currently being reviewed in 
https://github.com/googlesamples/android-architecture/pull/238

**Comment by monotonewang** [comment]
i am also looking for this...have solves@13kz
