### ISSUE TITLE
Why contract use a interface not a class

### ISSUE THREAD

**Issue by gunny520min** [googlesamples/android-architecture#245]
## this is the demo.who can tell me why StatisticsContract is a interface not a class!Thank you!
public interface StatisticsContract {

    interface View extends BaseView<Presenter> {

        void setProgressIndicator(boolean active);

        void showStatistics(int numberOfIncompleteTasks, int numberOfCompletedTasks);

        void showLoadingStatisticsError();

        boolean isActive();
    }

    interface Presenter extends BasePresenter {

    }
}

**Comment by JoseAlcerreca** [comment]
It's not necessary. 

However, it comes handy in the tablet sample.
