### ISSUE TITLE
Question about in-memmory cache

### ISSUE THREAD

**Issue by yamsergey** [googlesamples/android-architecture#247]
branch/sample/all

Hi. What's the reason to have in-memory cache? As I understood  you don't use it for `todo-mvp-loaders`, but for some reasons use it for other projects. I just wonder if SQLite is not good in performance? Also as I know it stores it's own cache in-memory. Please point me to some idea, why should I maintain my own in-memory cache?

**Comment by JoseAlcerreca** [comment]
It's your decision really, it depends on how much memory you want to use but generally it is a good idea to have some kind of in-memory cache for synchronous operations. 

For example: if you're in the details view and start editing the task, going to disk (SQLite in this case) would delay the opening of the new activity. You would have to show a progress bar and do the operation in the background, if you don't want your users to see jank or glitches. 

If you know your task is in memory, you can safely query the repository and it will return a value fast enough. SQLite might look fast, but there's no guarantee, as it's an IO operation.

**Comment by yamsergey** [comment]
Hm, thanks. Good point, I'll do some additional tests on it.
