### ISSUE TITLE
[question] Need explanation about usecase generic class and the way it is implemented

### ISSUE THREAD

**Issue by vahidhashemi** [googlesamples/android-architecture#248]
"todo-mvp-clean"

I was reading your source code and trying to find out the way you are thinking about business cases.
I'm wondering how do you come up with "UseCase.java" I really want to learn this way of thinking about projects and practice it on my own project.
Is there any references about this type of designing? book/video/website?

**Comment by JoseAlcerreca** [comment]
I'll Google that for you!
https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html
