### ISSUE TITLE
A FloatingActionButton bug crash in supportLibraryVersion = '23.2.1'

### ISSUE THREAD

**Issue by Andecy** [googlesamples/android-architecture#25]
java.lang.IllegalStateException: View can not be anchored to the the parent CoordinatorLayout

I think it crash in tasks_act.xml,                

app:layout_anchor="@id/coordinatorLayout"

will throw this.

I try to change to                 

app:layout_anchor="@id/contentFrame"

but it doesn't work

**Comment by JoseAlcerreca** [comment]
Since we're not using that version yet, I'm going to close this and we'll fix it when we bump the version. Thanks!
