### ISSUE TITLE
Combined sample - question

### ISSUE THREAD

**Issue by mvescovo** [googlesamples/android-architecture#250]
I love this repo! I'm still new to development in general and these examples are super helpful. However, I'm wondering, are any of the samples not compatible with any of the others? As far as I can tell, if I wanted to I could use the principles of all of the samples together in one app. Is this possible? Are they all complimentary? If not, which ones would prohibit the use of another one? Perhaps there could be another column in the "Samples-at-a-glance" page to show incompatibility (if it exists).
Thanks.

**Comment by JoseAlcerreca** [comment]
I don't think there's a strict incompatibility anywhere. For example, you _can_ use Loaders and Rx but I don't think if would beneficial.

Use this project to learn about the tools and decide for yourself :)
