### ISSUE TITLE
No comments todo-mvp

### ISSUE THREAD

**Issue by hayahyts** [googlesamples/android-architecture#251]
I really love the way this repository was structured, the coding style and everything but there are no comments to guide readers of the code. I really hope u do that

**Comment by JoseAlcerreca** [comment]
Thanks. We try to add comments in tricky parts or when it doesn't pollute the code. This project is aimed at intermediate developers so we assume some previous knowledge. If you find something hard to understand feel free to ask specifically. Closing now but feel free to reopen.
