### ISSUE TITLE
todo-mvp-clean: Domain package location

### ISSUE THREAD

**Issue by jchesterisidoro** [googlesamples/android-architecture#252]
I'm just confused with the hierarchy of directories of this app. Is it necessary to put the domain packages inside each "screen" directories? Isn't it better to move it to a separate folder?
These are my reasoning:

1. Any usecase can be called by a different presenter from a different folder
2. Reuse of the whole domain to another app will be easier
3. The clean architecture chart separates this as well.

**Comment by patrickds** [comment]
I believe it is because as stated in the Robert Martin [presentation](https://www.youtube.com/watch?v=Nsjsiz2A9mg&t=6s) about the clean architecture your top level directories should represent the application functionalities instead of the frameworks or layers. 
Also I see the folders in these samples in a different way, instead of thinking of it as as screen folder I think as a Action/Functionality folder.

With that said I agree with you at some level.

     "1. Any usecase can be called by a differente presenter from a differente folder"
             I agree that this can happen quite often in a bigger application and even with business models and I don't know the best solution. Maybe these shared classes could be in the top level directory but it kind breaks the structure logic state by Robert Martin. A better solution would be to create a top level for the common functionalities and have it contain both the functionalities and the common components in it. Like this:
          - app
                  - functionality

     "2. Reuse of the whole domain to another app will be easer"
           I never saw a case where someone would reuse the entire domain so I don't think I is common enough to consider changing the directories structure because of this.

     "3. The clena architecture char separates this as well."
          I believe that [chart](https://8thlight.com/blog/assets/posts/2012-08-13-the-clean-architecture/CleanArchitecture-8b00a9d7e2543fa9ca76b81b05066629.jpg) is only representing the dependency rule that states: "_Source code dependencies can only point inwards. Nothing in an inner circle can know anything at all about something in an outer circle._"

I hope this helps.
If someone has a better idea about how to structure the models and use cases that are reused between functionalities please help us =]

**Comment by gIliev94** [comment]
Hi, even though I`d be reiterating part of the jchesterisidoro`s question I still feel the need to ask it - how would the project directory structure be if it was meant to represent the layers of Clean Architecture?

I`m not experienced with it and I wasn`t able to spot the relevant files/folders to the architecture layers just by reading about the architecture and its principles.

I  am hoping to use this approach in an Anroid app with Kotlin for my diploma project(bachelor), so I`d very much appreciate if anyone would be willing to clarify which files/folders belong to which Clean Architecture layer in this particular example.

**Comment by JoseAlcerreca** [comment]
Probably better to continue on stackoverflow.
