### ISSUE TITLE
New branches request

### ISSUE THREAD

**Issue by punksta** [googlesamples/android-architecture#253]
Hey! Thanks for good examples of popular patterns like mvp and clean architecture. 

What do you think about adding branches with next things written with following patterns:

- Retain Fragments
- Services with different types of communication(BroadcastReceiver, ServiceConnection, Binding and IPC)
- Rest patterns A, B, C

I would like to see your vision of this classic things in context of popular in 2017 trends, like rxjava.

**Comment by JoseAlcerreca** [comment]
Hey punksta,

On retained Fragments, I think the best practice is to avoid them unless you want to persist state in a non-UI Fragment (my personal opinion, not sure if there's an official position). We could do that, but it would be too simple for a new branch.

I don't think the current TODO app can showcase receivers or IPC. Not sure it belongs to "architecture" either. We can't try to cover everything but if you think we need more samples or documentation I can raise the issue.

What do you mean with "Rest patterns A, B, C"?
