### ISSUE TITLE
I've converted the todo-mvp branch to kotlin

### ISSUE THREAD

**Issue by SerjSmor** [googlesamples/android-architecture#254]
https://github.com/SerjSmor/android-architecture

I would create a pull request if you are interested.

**Comment by JoseAlcerreca** [comment]
Thanks SerjSmor, that's great.

Before finding a reviewer, some questions and requests:
 - Is this a one-to-one translation or are you trying to be idiomatic?
 - Can you provide a README with a couple of examples where Kotlin made the code simple? Feel free to remove the todo-mvp content and just add "Based on the todo-mvp branch" with a link. This makes maintenance easier.
 - Please rename your branch to "todo-mvp-kotlin" 

Thank you!

**Comment by JoseAlcerreca** [comment]
For reference, a Kotlin conversion was already in progress #235

**Comment by JoseAlcerreca** [comment]
@SerjSmor ping!

**Comment by SerjSmor** [comment]
Hey Jose, 
1. I think it's mostly idiomatic due to the conversion being done by the JetBrain's tool, except for some parts that I had to patch because the conversion wasn't perfect. 
2. Will do
3. Done

**Comment by curioustechizen** [comment]
I also used Android Studio to perform the conversion and as I had expected the result is far from idiomatic. I did make some changes to make the code look more like Kotlin but it is still nowhere close to where it can be (it currently looks more like Java code written in Kotlin syntax). [Here's](https://github.com/curioustechizen/android-architecture/tree/dev-todo-mvp-kotlin) my progress so far.

**Comment by florina-muntenescu** [comment]
The mention of this Kotlin external sample was removed from the README because the sample was just converted from Java to Kotlin using the automatic converter, without any other modifications that improve the conversion. Also, tests were not passing. 
We're preparing an official sample that leverages Kotlin's language features in the project.

**Comment by codeslubber** [comment]
What happened here? I checked out: dev-todo-mvp-kotlin and the tests do not run.

**Comment by DougSig** [comment]
Can you be more specific? I just checked out that branch and all tests pass.

**Comment by codeslubber** [comment]
Brought it up in the Kotlin/Android channel and Jake said they pass too, but at the command line. For me, inside AS if I try to run the tests, it says the suite is empty. Yet running the tests in the Java version does work. He suggested I file an AS bug, which sounds reasonable.

**Comment by DougSig** [comment]
Ok got it, thanks for filing a bug.

**Comment by codeslubber** [comment]
Here is the link: https://issuetracker.google.com/issues/66724210.

**Comment by codeslubber** [comment]
Got it to work in 3.0, will not run tests in 2.3.x.
