### ISSUE TITLE
todo-mvp object creation query

### ISSUE THREAD

**Issue by benunderwood** [googlesamples/android-architecture#262]
Hi, I'm finding the examples very valuable, but I have a query. 
I'm going through the basic MVP example code, and there seems to be an inconsistency in TaskActivity.java. tasksFragment is created with the static factory method newInstance() (TasksActivity.java line 69), but mTasksPresenter is created directly through a constructor (TasksActivity.java line 75). Is there any particular reason for this?

Regards,
Ben.

**Comment by JoseAlcerreca** [comment]
The good practice for fragments is to only have an empty public constructor, so there's no reason for this. Maybe to corroborate that that's the way to create the fragment.
