### ISSUE TITLE
Video Explanation

### ISSUE THREAD

**Issue by abhi007tyagi** [googlesamples/android-architecture#263]
Is there any video explanation for these samples?
If not, please do so as some developers may not relate quickly to the patterns and the code style used in these samples. Also, it would be convenient to understand the architecture better.

**Comment by clivejefferies** [comment]
Maybe try these:

https://www.youtube.com/shared?ci=i0cGAyvupbs

https://www.youtube.com/shared?ci=m5IhjhKjIPk

Clive

**Comment by JoseAlcerreca** [comment]
Those are not about the architecture patterns we talk about here, but interesting nonetheless. 

I would start with
https://www.youtube.com/watch?v=QrbhPcbZv0I
from @florina-muntenescu.

**Comment by abhi007tyagi** [comment]
Thanks! I think hands-on is required to fully understand the concepts. It takes time to relate to things we do in MVC and its version in MVP/VM.

**Comment by robertoallende** [comment]
Hello

A silent reader here. What about Godfrey Nolan's talk at AnDevCon: MVC, MVP, MVVM Design Patterns. The video was released few weeks ago: https://www.youtube.com/watch?v=JV63czrUpbI

By the way, is anyone working on a sample following Yigit Boyar's MVC, the one using EventBus and Android Job Priority Queue ?. I've been working by my own on it, just for fun and I wonder if there should be interest to have a sample for that.

Kind Regards
Roberto Allende

**Comment by abhi007tyagi** [comment]
All these videos are good to get to know about different architectures Theoretically! I was more interested in some hands-on tutorial where we can get the idea through practical comparison between classic android architecture and MVP/VM in a step by step manner. That way it would be much faster for a developer to understand what is actually happening at the code level without getting distracted by the things that are just there for the logic and not part of the architecture.

**Comment by JoseAlcerreca** [comment]
Yes, once we have more patterns, we'll start generating content for beginners. Videos are very hard to maintain (impossible, actually!) but a codelab might be a good idea.

**Comment by abhi007tyagi** [comment]
Codelab would be great. As a suggestion, please show by converting an existing app in classic Android into a same version now using different architectures.
