### ISSUE TITLE
This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build system

### ISSUE THREAD

**Issue by HaagenDaz** [googlesamples/android-architecture#27]
This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build system...why

**Comment by malmstein** [comment]
Hi @HaagenDaz, have you tried checking any of the branches out? `master` won't allow you to build anything.

**Comment by HaagenDaz** [comment]
@malmstein Every branch is a single progect?

**Comment by malmstein** [comment]
Every branch is a showcase of a different architecture, check https://github.com/googlesamples/android-architecture#samples out

**Comment by HaagenDaz** [comment]
ye, I  check https://github.com/googlesamples/android-architecture#samples out and checkout todo-mvp-loaders branch. But it prompt "This project does not use the Gradle build system. " . Now I open the todoapp directory with android studio, it work.

**Comment by sadegh** [comment]
This occurs to me as well. I cloned the repo, then I checked out `todo-mvp` branch, then I opened the project with android studio. but still getting `This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build system.` error and it does not recognized `.java` classes.
![screen shot 2017-03-18 at 8 04 11 am](https://cloud.githubusercontent.com/assets/657684/24070260/8c024a2c-0bb1-11e7-9712-c306b3d38dd9.png)

**Comment by slimgt** [comment]
close your project then backup it, delete the ".idea" folder and all *.iml files in your project then reopen it

**Comment by 5529** [comment]
Hello, did you found solution for this?  This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build system.

**Comment by akshaydhone** [comment]
facing the same issue

**Comment by JoseAlcerreca** [comment]
You need to 
- check out one of the branches
- open the todoapp, not the root directory.
