### ISSUE TITLE
TODO-DataBinding-RxJava: why use android-apt, which has been deprecated from gradle 2.2?

### ISSUE THREAD

**Issue by softboy99** [googlesamples/android-architecture#276]
in the master, there is no android-apt plugin, which has been deprecated after gradle 2.2 released. please remove it. Thanks.

**Comment by adstro** [comment]
See https://bitbucket.org/hvisser/android-apt/wiki/Migration and http://www.littlerobots.nl/blog/Whats-next-for-android-apt for details
