### ISSUE TITLE
CircleCI: Copying junit results for better reporting

### ISSUE THREAD

**Issue by oldergod** [googlesamples/android-architecture#283]
CircleCI has nice reporting for test results. We would just need to copy those result files into `$CIRCLE_TEST_REPORTS`.

Once done, CircleCI would be more explicit about those results which would help addressing failing tests.  
Example when all tests passed:  
![image](https://cloud.githubusercontent.com/assets/1767669/22814013/78096f4e-ef93-11e6-811b-45600fc7bad3.png)

This could easily be achieved by adding a post step copying `*.xml` files from `$CIRCLE_ARTIFACTS/` once the results are copied from Firebase.

**Comment by JoseAlcerreca** [comment]
+1, want to take it?
