### ISSUE TITLE
(todo-databinding) Build failed of DataBinding in todo-databinding branch after upgrade android studio 2.3 and gradle 3.3-all

### ISSUE THREAD

**Issue by JuwanZhu** [googlesamples/android-architecture#293]
>  symbol:   variable BR
  location: class TasksViewModel
/home/javan/Projects/Github/android-architecture/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksViewModel.java:103: error: cannot find symbol
        notifyPropertyChanged(BR.notEmpty);
                              ^
  symbol:   variable BR
  location: class TasksViewModel
/home/javan/Projects/Github/android-architecture/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksViewModel.java:104: error: cannot find symbol
        notifyPropertyChanged(BR.tasksAddViewVisible);
                              ^
  symbol:   variable BR
  location: class TasksViewModel
/home/javan/Projects/Github/android-architecture/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksFragment.java:90: error: cannot find symbol
        TasksFragBinding tasksFragBinding = TasksFragBinding.inflate(inflater, container, false);
        ^
  symbol:   class TasksFragBinding
  location: class TasksFragment
/home/javan/Projects/Github/android-architecture/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksFragment.java:90: error: cannot find symbol
        TasksFragBinding tasksFragBinding = TasksFragBinding.inflate(inflater, container, false);
                                            ^
  symbol:   variable TasksFragBinding
  location: class TasksFragment
/home/javan/Projects/Github/android-architecture/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksFragment.java:291: error: cannot find symbol
            TaskItemBinding binding;
            ^
  symbol:   class TaskItemBinding
  location: class TasksAdapter
/home/javan/Projects/Github/android-architecture/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksFragment.java:297: error: cannot find symbol
                binding = TaskItemBinding.inflate(inflater, viewGroup, false);
                          ^
  symbol:   variable TaskItemBinding
  location: class TasksAdapter
/home/javan/Projects/Github/android-architecture/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/taskdetail/TaskDetailFragment.java:87: error: cannot find symbol
        mViewDataBinding = TaskdetailFragBinding.bind(view);
                           ^
  symbol:   variable TaskdetailFragBinding
  location: class TaskDetailFragment
/home/javan/Projects/Github/android-architecture/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/addedittask/AddEditTaskFragment.java:93: error: cannot find symbol
            mViewDataBinding = AddtaskFragBinding.inflate(inflater, container, false);
                               ^
  symbol:   variable AddtaskFragBinding
  location: class AddEditTaskFragment
Note: /home/javan/Projects/Github/android-architecture/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksViewModel.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
20 errors
:app:compileMockDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileMockDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.472 secs

-----

can't build success after upgrade android studio 2.3 android gradle 3.3-all. I didn't change anything.  How could I solve it ?

**Comment by JoseAlcerreca** [comment]
Have you rebuilt? looks like the bindings weren't generated.

**Comment by JuwanZhu** [comment]
Hi @JoseAlcerreca , `./gradlew clean assembleDebug` `./gradlew assembleDebug` I have tried, but also build failed. 


Run `git diff` : 

```
diff --git a/todoapp/build.gradle b/todoapp/build.gradle
index 780b95d..f745aea 100644
--- a/todoapp/build.gradle
+++ b/todoapp/build.gradle
@@ -4,7 +4,7 @@ buildscript {

     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:2.2.3'
+        classpath 'com.android.tools.build:gradle:2.3.0'

         // Plugin to help with annotation processing
         classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
@@ -31,7 +31,7 @@ ext {
     minSdkVersion = 10
     targetSdkVersion = 24
     compileSdkVersion = 24
-    buildToolsVersion = '24.0.2'
+    buildToolsVersion = '25.0.0'

     // App dependencies
     supportLibraryVersion = '24.2.0'
diff --git a/todoapp/gradle/wrapper/gradle-wrapper.properties b/todoapp/gradle/wrapper/gradle-wrapper.properties
index 8f3357b..958f361 100644
--- a/todoapp/gradle/wrapper/gradle-wrapper.properties
+++ b/todoapp/gradle/wrapper/gradle-wrapper.properties
@@ -1,6 +1,6 @@
-#Mon Feb 15 18:30:34 GMT 2016
+#Mon Mar 06 09:13:12 CST 2017
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
```

**Comment by JuwanZhu** [comment]
After Add `    apt 'com.android.databinding:compiler:2.3.0' ` to `build.gradle(app)`, Builded success. the reason why I build failed is the version of databinding compiler?

**Comment by JoseAlcerreca** [comment]
Yes, that makes sense!
