### ISSUE TITLE
Question : Does Business logic in MVP on View is a good practise?

### ISSUE THREAD

**Issue by bhushanraut1811** [googlesamples/android-architecture#296]
Branch name: todo-mvp

      @Override
         public void setProgressIndicator(boolean active) {
         if (active) {
            mStatisticsTV.setText(getString(R.string.loading));
        } else {
            mStatisticsTV.setText("");
        }
    }

    @Override
    public void showStatistics(int numberOfIncompleteTasks, int numberOfCompletedTasks) {
        if (numberOfCompletedTasks == 0 && numberOfIncompleteTasks == 0) {
            mStatisticsTV.setText(getResources().getString(R.string.statistics_no_tasks));
        } else {
            String displayString = getResources().getString(R.string.statistics_active_tasks) + " "
                    + numberOfIncompleteTasks + "\n" + getResources().getString(
                    R.string.statistics_completed_tasks) + " " + numberOfCompletedTasks;
            mStatisticsTV.setText(displayString);
        }
    }
Here we are doing some business logic on our View, shouldn't this to be part of presenter and then presenter will notify what to show to the View.

**Comment by JoseAlcerreca** [comment]
Yep, you could generate the strings in the presenter. If I had to do it again I would move it to the presenter and unit test it, as it's relatively complex logic.

**Comment by bhushanraut1811** [comment]
@JoseAlcerreca thanks
