### ISSUE TITLE
New sample: MVVM architecture with data binding, Dagger2 and RxJava.

### ISSUE THREAD

**Issue by nativ18** [googlesamples/android-architecture#299]
Hi guys, I was wondering if you'll find this demo app(desc in the title) useful and if so than I would like to create and share it here.

**Comment by JoseAlcerreca** [comment]
That amount of tools would have to be an external sample:
https://github.com/googlesamples/android-architecture/wiki/External-samples

We'll add it to the main README after a small review.

**Comment by nativ18** [comment]
Sure, I'll post here the link to the project's repository once I've done working on it.

**Comment by nativ18** [comment]
Hi, I've created the sample app. 

I didn't write yet the README.md file, if you'd like it to be completed before reviewing the code than let me know.

The code style is aligned with google's code style for contributors document.

Regards,
Nativ

**Comment by JoseAlcerreca** [comment]
This is not the todo app, it's something else.

**Comment by nativ18** [comment]
@JoseAlcerreca can you please elaborate?

**Comment by JoseAlcerreca** [comment]
We create this app in this project: https://github.com/googlesamples/android-architecture/wiki/To-do-app-specification

**Comment by nativ18** [comment]
Thanks for the response. Actually I didn't find there a sample app with that same stack but I totally agree that one should be developed from the current sample apps and not as a totally new external app.
