### ISSUE TITLE
[all] Git Commit Message Style Guide

### ISSUE THREAD

**Issue by jpventura** [googlesamples/android-architecture#300]
# Git Commit Message Style Guide

This is only a suggestion/discussion about adopting a _commit message style guide_

The following text was transcripted from [Udacity Git Commit Message Style Guide](https://udacity.github.io/git-styleguide/). It also can be combined with other ideas, such as [commit message emojis](https://github.com/dannyfritz/commit-message-emoji).

## Introduction
There are many opinions on the _ideal_ style in the world of development. Therefore, in order to reduce the confusion on what style students should follow during the course of their projects, we urge all contributors to refer to this style guide for this project.

### Message Structure
A commit messages consists of three distinct parts separated by a blank line: the title, an optional body and an optional footer. The layout looks like this:

    type: subject

    body

    footer

The title consists of the type of the message and subject.

### The Type
The type is contained within the title and can be one of these types:
- **feat:** a new feature
- **fix:** a bug fix
- **docs:** changes to documentation
- **style:** formatting, missing semi colons, etc; no code change
- **refactor:** refactoring production code
- **test:** adding tests, refactoring test; no production code change
- **chore:** updating build tasks, package manager configs, etc; no production code change

### The Subject
Subjects should be no greater than **50 characters**, should begin with a capital letter and do not end with a period.

Use an imperative tone to describe what a commit does, rather than what it did. For example, use change; not changed or changes.

### The Body
Not all commits are complex enough to warrant a body, therefore it is optional and only used when a commit requires a bit of explanation and context. Use the body to explain the **what** and **why** of a commit, not the how.

When writing a body, the blank line between the title and the body is required and you should limit the length of each line to no more than 72 characters.

### The Footer
The footer is optional and is used to reference issue tracker IDs.

### Example Commit Message

    feat: Summarize changes in around 50 characters or less

    More detailed explanatory text, if necessary. Wrap it to about 72
    characters or so. In some contexts, the first line is treated as the
    subject of the commit and the rest of the text as the body. The
    blank line separating the summary from the body is critical (unless
    you omit the body entirely); various tools like `log`, `shortlog`
    and `rebase` can get confused if you run the two together.

    Explain the problem that this commit is solving. Focus on why you
    are making this change as opposed to how (the code explains that).
    Are there side effects or other unintuitive consequences of this
    change? Here's the place to explain them.

    Further paragraphs come after blank lines.

     - Bullet points are okay, too

     - Typically a hyphen or asterisk is used for the bullet, preceded
       by a single space, with blank lines in between, but conventions
       vary here

    If you use an issue tracker, put references to them at the bottom,
    like this:

    Resolves: #123
    See also: #456, #789

**Comment by LucasMoresco** [comment]
👍

**Comment by JoseAlcerreca** [comment]
Many thanks! 

However, I don't think we need this. I prefer to deal with and teach newbies rather than to make everyone read and comply with a long list of rules.

**Comment by jpventura** [comment]
@JoseAlcerreca, this and the [Fernando Cejas](https://github.com/android10/Android-CleanArchitecture) project became the main references in community about Android  architecture. 

Several developers will start their own projects getting inspired by this one. Thus I believe that adopting some style will drive people how to organize their code history as well ;-)

**Comment by JoseAlcerreca** [comment]
We prefer small and frequent commits. If you enforce that style people will simply commit less often.

**Comment by rahulgurnani** [comment]
Hi, Any specific commit format to follow for addressing pull request review comments?
