### ISSUE TITLE
[todo-mvp] when will it getTasks from the local db?

### ISSUE THREAD

**Issue by ahunigel** [googlesamples/android-architecture#312]
The loadTasks() will forceUpdate for the 1st time, and get data from remote source, then save to in memory cache and local db. 

However, I find out there is no chance to get tasks from the local db, because the in memory cache will never be null and not dirty at the same time, so how does the local db work?

'''
    @Override
    public void getTasks(@NonNull final LoadTasksCallback callback) {
        checkNotNull(callback);

        // Respond immediately with cache if available and not dirty
        if (mCachedTasks != null && !mCacheIsDirty) {
            callback.onTasksLoaded(new ArrayList<>(mCachedTasks.values()));
            return;
        }

        if (mCacheIsDirty) {
            // If the cache is dirty we need to fetch new data from the network.
            getTasksFromRemoteDataSource(callback);
        } else {
            // Query the local storage if available. If not, query the network.
            mTasksLocalDataSource.getTasks(new LoadTasksCallback() {
                @Override
                public void onTasksLoaded(List<Task> tasks) {
                    refreshCache(tasks);
                    callback.onTasksLoaded(new ArrayList<>(mCachedTasks.values()));
                }

                @Override
                public void onDataNotAvailable() {
                    getTasksFromRemoteDataSource(callback);
                }
            });
        }
    }
'''

**Comment by JoseAlcerreca** [comment]
Dup of #123, we don't have a real remote API so we simplified. This sample is not about the data layer.

**Comment by ahunigel** [comment]
@JoseAlcerreca I got your point. Thanks. My real concern is how to make the cache policy works better. Maybe a limit for the in memory is reasonable, such as max size, timeout, etc.

**Comment by JoseAlcerreca** [comment]
Yep it's a complex problem that depends a lot on the requirements of the app.

**Comment by ahunigel** [comment]
@JoseAlcerreca do you know any other samples about this topic? that will be helpful for me. 
Thanks a lot. BR
