### ISSUE TITLE
todo-mvvm-databinding: a TextView "Add a TO-DO item +" always visible despite the filter's type

### ISSUE THREAD

**Issue by jkozh** [googlesamples/android-architecture#315]
todo-mvvm-databinding

In TasksViewModel I've noticed that you set the current task filtering type, and in switch cases you do tasksAddViewVisible.set(true) set to be true only for the case ALL_TASKS. But that view stays visible in ACTIVE_TASKS, and COMPLETED_TASKS.

**Comment by JoseAlcerreca** [comment]
Yep, well spotted. Thanks.
