### ISSUE TITLE
[todo-mvp-rxjava] setPresenter is called twice in addedittask module

### ISSUE THREAD

**Issue by kkamaraj** [googlesamples/android-architecture#320]
From the code walkthrough it looks like we call setPresenter(presenter) twice in addedittask module.
1. Called from AddEditTaskActivity using Fragment instance (redundant??)
2. Called from AddEditTaskPresenter constructor (Right place)

From the other modules it looks like calling setPresenter from constructor of a presenter is the right place for this. Please opine.

Created PR for this issue - https://github.com/kkamaraj/android-architecture/pull/1

**Comment by Res2013** [comment]
I'm very confused about it!

**Comment by florina-muntenescu** [comment]
Issue fixed. Tests added to cover the `view.setPresenter` call in the constructor, also.
Thank you, @kkamaraj for reporting the issue!
