### ISSUE TITLE
[todo-mvp-loaders] A lot of instances of the loader are being created.

### ISSUE THREAD

**Issue by yadavvi91** [googlesamples/android-architecture#321]
A lot of loaders are being created in the `todo-mvp-loaders` branch. I have logged the `callbacks` of the `LoaderManager.LoaderCallbacks` are here are some logs -

    I/TasksPresenter: onCreate()TasksLoader{cfba741 id=0}
    I/TasksPresenter: initLoader: 1
    I/TasksPresenter: onCreateLoader: 1
    I/TasksPresenter: onLoadFinished: TasksLoader{cfba741 id=1}
    I/TasksPresenter: onCreate()TasksLoader{45d2d8f id=0}
    I/TasksPresenter: initLoader: 1
    I/TasksPresenter: onLoadFinished: TasksLoader{cfba741 id=1}
    I/TasksPresenter: onCreate()TasksLoader{de425f id=0}
    I/TasksPresenter: initLoader: 1
    I/TasksPresenter: onLoadFinished: TasksLoader{cfba741 id=1}
    I/TasksPresenter: onCreate()TasksLoader{7fad32f id=0}
    I/TasksPresenter: initLoader: 1
    I/TasksPresenter: onLoadFinished: TasksLoader{cfba741 id=1}
    I/TasksPresenter: onCreate()TasksLoader{877dfff id=0}
    I/TasksPresenter: initLoader: 1
    I/TasksPresenter: onLoadFinished: TasksLoader{cfba741 id=1}

As we can see a **lot** of instance of the `Loader` are created (one in every `onCreate()` of the `Activity`).

Also, we aren't supposed to use `setRetainInstance()` in a `Fragment` as mentioned by [Ian Lake](https://medium.com/google-developers/making-loading-data-on-android-lifecycle-aware-897e12760832) in his blog post about `Loaders`.

One solution is getting the loader instances from the `LoaderManager` something like this - 

    TasksLoader tasksLoader = getSupportLoaderManager().getLoader(TASKS_QUERY);
    if (tasksLoader == null) {
        tasksLoader = new TasksLoader(getApplicationContext(), repository);
    }

However, I am unable to type cast the generic `Loader<D>` to `TasksLoader`. Any other suggestions?

**Comment by yadavvi91** [comment]
@malmstein any updates on this issue?

**Comment by florina-muntenescu** [comment]
loaders branch is deprecated.
