### ISSUE TITLE
[todo-mvp-loaders] {question} Presenter should not have loaders, right?

### ISSUE THREAD

**Issue by Ndrocchietto** [googlesamples/android-architecture#323]
Dear All, why the presenter has
 in `TaskPresenter.create()` this line below?
` mLoaderManager.initLoader(TASKS_QUERY, null, this);`

why adding a LoaderManager into the presenter, it is not against the meaning that in the presenter should not stay any android logic but only the interfaces?

**Comment by JoseAlcerreca** [comment]
That's the goal, but Loaders will bleed into the presenter at some point. It's very coupled with the framework, which is definitely a disadvantage. In this case it doesn't affect testing too much so it's fine.
