### ISSUE TITLE
Isn't inefficient loading whole list again when task completed?

### ISSUE THREAD

**Issue by jkj8790** [googlesamples/android-architecture#326]
First, I'm really confusing with functional paradigm.

And This part looks so strange for me -  Request change todo's completeness to repository, and load "all" tasks again.

I think It happened because of Immutability, but it seems inefficient to do so.
What If loading is long task like network? I think it cause additional traffic. What we have to do is just completing todo!

Please tell me what's wrong with me. 

--------------------- Added project detail for question context.
I'm developing file explorer applying todo-mvp-rxjava structure.
What I having trouble is file select feature for copy, move, and so on.
I think selection should not request to repository. Because it's not saved. It's just for view's attribute. I want to change model's selected attribute, but I can't because model is immutable. And It looks inappropriate too. Should I just save position's of selected tasks?

**Comment by JoseAlcerreca** [comment]
This sample showcases how to organize code and the different components. Its focus is not on the data layer so there are many inefficiencies that you might want to optimize.
