### ISSUE TITLE
[todo-mvvm] Architecture Components sample

### ISSUE THREAD

**Issue by gaurav414u** [googlesamples/android-architecture#337]
I want to integrate the latest architectural components (ViewModel, LiveData, LifeCycleOwner) into the todo-mvvm. Should there be a new branch with the name [todo-mvvm-{newandroidarch/somethingelse}] or should I start editing in this branch only?

**Comment by ber4444** [comment]
+1

(also, for reference, he is talking about https://developer.android.com/topic/libraries/architecture/guide.html)

**Comment by gaurav414u** [comment]
Exactly. Thanks!

**Comment by gaurav414u** [comment]
@ber4444 I have started working on it here: https://github.com/gaurav414u/android-architecture/tree/todo-mvvm-databinding_newarch. Please feel free to observe and let me know if something needs to be altered.
Thanks

**Comment by JoseAlcerreca** [comment]
We're working on an official branch for this but feel free to publish yours, we're still defining good and bad patterns and more ideas are welcomed.

**Comment by gaurav414u** [comment]
@JoseAlcerreca , I have started working, but found out that the DataBinding is not lifecycle aware yet. It will be there once  the lifecycle hits 1.0 stable api - as per Yigit.
Should I submit a pull request for this unfinished work? 
I am new over here :)

**Comment by gaurav414u** [comment]
@JoseAlcerreca Can we reopen this issue to discuss on [linkToPullRequestInMyFork](https://github.com/gaurav414u/android-architecture/pull/1)?
Thanks

**Comment by JoseAlcerreca** [comment]
Cool, let's discuss on your fork.

**Comment by JoseAlcerreca** [comment]
We now have dev- branches for both lifecycle-aware components and Room.

https://github.com/googlesamples/android-architecture
