### ISSUE TITLE
Question: Why do you suggests to have a separate Activity for each feature?

### ISSUE THREAD

**Issue by shrikantballal** [googlesamples/android-architecture#342]
Hi,

I have a question. Why do you suggests to have a separate Activity for each feature? It makes sense to have a separate Fragment for each screen but why to have a new Activity-Fragment combination for each usecase?
Shouldn't this be a problem to implement shared element transitions? As shared element transitions can happen between Fragment-Fragment or Activity-Activity.

**Comment by JoseAlcerreca** [comment]
It's completely fine to use a single activity with multiple fragments or even multiple activities without fragments.
