### ISSUE TITLE
[todo-mvp]Doubt with a Android Unit Test

### ISSUE THREAD

**Issue by ychongjie** [googlesamples/android-architecture#344]
Hello, I just start to learn this project, and I have a small doubt with the Android Unit Test part.

The class TasksLocalDataSourceTest has a method activateTask_retrievedTaskIsActive:

    @Test
    public void activateTask_retrievedTaskIsActive() {
        // Initialize mock for the callback.
        TasksDataSource.GetTaskCallback callback = mock(TasksDataSource.GetTaskCallback.class);

        // Given a new completed task in the persistent repository
        final Task newTask = new Task(TITLE, "");
        mLocalDataSource.saveTask(newTask);
        mLocalDataSource.completeTask(newTask);

        // When activated in the persistent repository
        mLocalDataSource.activateTask(newTask);

        // Then the task can be retrieved from the persistent repository and is active
        mLocalDataSource.getTask(newTask.getId(), callback);

        verify(callback, never()).onDataNotAvailable();
        verify(callback).onTaskLoaded(newTask);

        assertThat(newTask.isCompleted(), is(false));
    }

I think this method doesn't really fulfil it's intention, right? Because the object newTask is never changed, when I remove `mLocalDataSource.activateTask(newTask)`, this test can still pass.

**Comment by JoseAlcerreca** [comment]
Activated is the default, that's why it still passes. There's another one that tests the opposite.
