### ISSUE TITLE
[todo-mvp-clean] Using domain models in data layer

### ISSUE THREAD

**Issue by knightkill** [googlesamples/android-architecture#348]
(In reference to 'Task' model from domain layer used in repository pattern which belongs to data layer)
Isn't it required to use model per layer to separate domain layer from data layer according to clean architecture?
Doesn't break the dependency rule?

**Comment by JoseAlcerreca** [comment]
Yep, you're right. In a real app you will probably have to do it anyway.

**Comment by knightkill** [comment]
@JoseAlcerreca Thanks. Just needed to confirm. Will probably try to implement it and pull :)
