### ISSUE TITLE
[todo-mvp-dagger] Dagger sample implemented using AndroidInjector

### ISSUE THREAD

**Issue by hshahdoost** [googlesamples/android-architecture#356]
AndroidInjector is a cleaner and more sophisticated way of implementing dagger. Since this is the main sample of learning Dagger in android, I suggest that the source changes to a more practical approach.

**Comment by digitalbuddha** [comment]
Thank you for the request. We will have the dagger-mvp sample updated to use `AndroidInjector` shortly. #375
