### ISSUE TITLE
[dev-todo-mvvm-live] Merging the room changes from [dev-todo-mvp-room]

### ISSUE THREAD

**Issue by gaurav414u** [googlesamples/android-architecture#357]
I was just looking into `dev-todo-mvvm-live` and `dev-todo-mvp-room`. I think dev-todo-mvp-room's changes should be merged in dev-todo-mvvm-live as well. This will make the `dev-todo-mvvm-live` to be the sole branch to refer to for the new arch components todo sample.
Thoughts?

**Comment by JoseAlcerreca** [comment]
This will happen when arch components hits 1.0. We'll use room for all branches.

**Comment by gaurav414u** [comment]
@JoseAlcerreca Awesome!
