### ISSUE TITLE
Error:Entities and Pojos must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type).

### ISSUE THREAD

**Issue by shakil807g** [googlesamples/android-architecture#364]
Error:Entities and Pojos must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type).

**Comment by JoseAlcerreca** [comment]
Need more info

**Comment by saihiroshi** [comment]
the same error while build. 



e: エラー: Entities and Pojos must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type).
e: 

e:   Tried the following constructors but they failed to match:
e:   Integer(int) : [value : null]
e:   Integer(java.lang.String) : [s : null]
e: エラー: Entities and Pojos must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type).
e: 

```
data class UserWithCommunityIds(
        @Embedded
        var user: User? = null,

        @Relation(parentColumn = "id",
                entityColumn = "users_id",
                entity = CommunityUsers::class,
                projection = arrayOf("communities_id"))
        var communityIds: List<Int>? = null
)
```

and me add manually add construct

```
constructor() : this(null, null)
```

not work.

**Comment by rs146** [comment]
I am encountering the same issue as above. I have the following entities:

```
@Entity(tableName = "Person")
data class Person(@PrimaryKey var id: Int,
                  var firstName: String,
                  var surname: String,
                  var age: Int,
                  var numberOfHobbies: Int)

@Entity(tableName = "Skill")
data class Skill(@PrimaryKey var id: Int,
                 var skillName: String = "")

@Entity(tableName = "PersonSkill")
data class PersonSkill(var personId: Int,
                       var skillId: Int) {
    constructor() : this(0, 0)

    @field:PrimaryKey(autoGenerate = true)
    var id: Int = 0
}
```

And the following relationships:

```
data class SkillWithPersons(
        @Embedded val skill: Skill = Skill(0, "UNKNOWN"),
        @Relation(
                parentColumn = "id",
                entityColumn = "skillId",
                entity = PersonSkill::class
        ) val personIds: List<Int> = emptyList()
) {
        constructor() : this(Skill(0, "UNKNOWN"), emptyList())
}

data class PersonWithSkills(
        @Embedded val person: Person = Person(0, "UNKNOWN", "UNKNOWN", 0, 0),
        @Relation(
                parentColumn = "id",
                entityColumn = "personId",
                entity = PersonSkill::class
        ) val skillIds: List<Int> = emptyList()
) {
        constructor(): this(Person(0, "UNKNOWN", "UNKNOWN", 0, 0), emptyList())
}
```

And I have tried everything, and yet it does not work. I keep getting the error:

```
/Users/rahulsingh/git-android/android-sample-sdk/app/build/tmp/kapt3/stubs/debug/uk/co/ostmodern/persistence/entity/PersonSkill.java:32: error: Room cannot pick a constructor since multiple constructors are suitable. Try to annotate unwanted constructors with @Ignore.
e: 

e:     public PersonSkill(int personId, int skillId) {
e:            ^
e: /Users/rahulsingh/git-android/android-sample-sdk/app/build/tmp/kapt3/stubs/debug/uk/co/ostmodern/persistence/entity/PersonSkill.java:36: error: Room cannot pick a constructor since multiple constructors are suitable. Try to annotate unwanted constructors with @Ignore.
e: 

e:     public PersonSkill() {
e:            ^
e: error: Entities and Pojos must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type).
e: 

e:   Tried the following constructors but they failed to match:
e:   Integer(int) : [value : null]
e:   Integer(java.lang.String) : [s : null]
e: error: Entities and Pojos must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type).
e: 

e: /Users/rahulsingh/git-android/android-sample-sdk/app/build/tmp/kapt3/stubs/debug/uk/co/ostmodern/persistence/entity/PersonWithSkills.java:7: error: Cannot find setter for field.
e: 

e:     private final uk.co.ostmodern.persistence.entity.Person person = null;
e:                                                             ^
e: /Users/rahulsingh/git-android/android-sample-sdk/app/build/tmp/kapt3/stubs/debug/uk/co/ostmodern/persistence/entity/PersonWithSkills.java:10: error: Cannot find setter for field.
e: 

e:     private final java.util.List<java.lang.Integer> skillIds = null;
```

**Comment by corneliouzbett** [comment]
getting the same problems any help

**Comment by Harisiqbal7465** [comment]
@Entity (tableName = "tblOwnRateList")
data class OwnRateList(
    @PrimaryKey(autoGenerate = false)
    val ownRateListId: Int,
    val ownRateListName: String,
){
    @Ignore
    var sizeList: Long = 0L  // Ignore value 
}

main(){
                val list = OwnRateList(0, "ownList")
                list.sizeList = countSize // Set value
               val size = list.sizeList //Get value 

}

**Comment by moradi-morteza** [comment]
i have same erro : 
```
Entities and POJOs must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type). - kotlin.Unit
````

this is my model : 
```kotlin
@Entity
data class User(
    @PrimaryKey val id: Int,
    val name: String?,
    val email: String?,
    val avatar: String?
)
```

this is my gradle : 
```groovy
    // room
    def room_version = "2.4.1"
    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
```

gradle version : 
```groovy
classpath "com.android.tools.build:gradle:7.0.4"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
```

and finaly kotlin version :  1.6.0

why this happen?

**Comment by Shashikant405044** [comment]
Entity(tableName = "movie_table")
data class TvMovies(
    @PrimaryKey(autoGenerate = true)
    @SerializedName("id")
    val id: Int,
    @SerializedName("overview")
    val overview: String,

    @SerializedName("poster_path")
    val poster_path: String,

    @SerializedName("first_air_date")
    val first_air_date: String,

    @SerializedName("name")
    val name: String,
)

Entities and POJOs must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type). - kotlin.Unit

**Comment by OgabekDev** [comment]
> i have same erro :
> 
> ```
> Entities and POJOs must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type). - kotlin.Unit
> ```
> 
> this is my model :
> 
> ```kotlin
> @Entity
> data class User(
>     @PrimaryKey val id: Int,
>     val name: String?,
>     val email: String?,
>     val avatar: String?
> )
> ```
> 
> this is my gradle :
> 
> ```groovy
>     // room
>     def room_version = "2.4.1"
>     implementation "androidx.room:room-runtime:$room_version"
>     kapt "androidx.room:room-compiler:$room_version"
>     implementation "androidx.room:room-ktx:$room_version"
> ```
> 
> gradle version :
> 
> ```groovy
> classpath "com.android.tools.build:gradle:7.0.4"
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
> ```
> 
> and finaly kotlin version : 1.6.0
> 
> why this happen?

Who has a solution of this error

**Comment by jaaliska** [comment]
I had the same error. The error disappeared when i corrected the typo. 

`@Dao
interface UserDao {

    @Insert()
    fun insert(value: RoomUser)

    @Query("SELECT * FROM user")
    fun getAll(): List<UserDao > // the typo! I return the Dao interface instead Entity
}`

**Comment by nicklauscott** [comment]
> I had the same error. The error disappeared when i corrected the typo.
> 
> ```kotlin
> @Dao
> interface UserDao {
> 
>     @Insert()
>     fun insert(value: RoomUser)
> 
>     @Query("SELECT * FROM user")
>     fun getAll(): List<UserDao> // the typo! I return the Dao interface instead Entity
> }
> ```

Thanks. I was making the same mistake.
