### ISSUE TITLE
[todo-mvp] Initialize presenter inside fragment

### ISSUE THREAD

**Issue by pedrofraca** [googlesamples/android-architecture#368]
Hi,

Want to ask about initializing presenter inside fragment. I know what are the benefits of doing this from outside, but want to ask about your opinion of initializing a default presenter, repository... directly on the fragment/view onViewCreated(). One benefit I see now is to have less code on the activity and avoiding to copy code if the fragment/view is used several times on the app (it's true that this can be solved having an activity with the code and extend from there). Another point which is not really clear for me is about fragment lifecycle, can a fragment be killed and be automatically rebuilt by the system? For instance: is possible for a not visible fragment (replaced after a fragmentManager transaction) to be killed without it's parent activity being also killed?. If thats the case, we should be listening for changes in the BackStack entries to recreate the presenter, which could be pretty tedious. 

Thanks.

**Comment by JoseAlcerreca** [comment]
Both are valid, with pros and cons. I suggest searching on SO or asking there.
