### ISSUE TITLE
[todo-mvvm-databinding] Scrolling if there are more TODOs than fits on the screen calls repository methods if checkbox value changes

### ISSUE THREAD

**Issue by Zhuinden** [googlesamples/android-architecture#371]
Scrolling if there are more TODOs than fits on the screen calls repository methods if checkbox value changes. This is because two-way data binding calls `setCompleted()` even when list item check box value is set to new task completed value.

**Comment by JoseAlcerreca** [comment]
We removed that call when we updated to Room. Feel free to reopen if it's not fixed.

**Comment by demoNo** [comment]
This issue has bot been fixed.
