### ISSUE TITLE
[todo-mvvm-databinding] Task class is not actually immutable (despite docs claim)

### ISSUE THREAD

**Issue by Zhuinden** [googlesamples/android-architecture#373]
https://github.com/googlesamples/android-architecture/blob/4c41b4a163e5698185501a2232c7988024ab0383/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/data/Task.java#L121-L123

`Task.completed` is mutable and modified in the object in `TaskViewModel`

https://github.com/googlesamples/android-architecture/blob/4c41b4a163e5698185501a2232c7988024ab0383/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/TaskViewModel.java#L95

**Comment by JoseAlcerreca** [comment]
We added Room and fixed this.
