### ISSUE TITLE
Order of resource releasing in life cycle events

### ISSUE THREAD

**Issue by maxim-pandra** [googlesamples/android-architecture#377]
todo-mvp-rxjava  TasksFragment

Shouldn't we unsubscribe, and release other resources before `super.onPause()` ?
Please explain, I am a little confused. I was thinking that we should release resources in a revers order, but there, order of method calls is the same as in `onResume() 
`

    @Override
    public void onPause() {
        super.onPause();
        mPresenter.unsubscribe(); //shouldn't be before super.onPause()?
    }

**Comment by florina-muntenescu** [comment]
Feel free to create a PR that fixes this for all screens.
