### ISSUE TITLE
What scenario we need @Nullable over onCreateView of the fragment?

### ISSUE THREAD

**Issue by vsay01** [googlesamples/android-architecture#379]
Hi, this is just a question.

I looked at the fragment files and i see

```
@Nullable
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {}
```

I tried to understand what scenario that it's okay for the fragment onCreateView to return null, since it's the main content of the activity.

For instance, **@Nullable** for **Bundle** in **onCreate** of the activity is straight forward since **Bundle** can be null.

Could anyone point out?

**Comment by florina-muntenescu** [comment]
`Fragment`s that don't have a UI can return null.  
Check out the documentation for [`Fragment#onCreateView`](https://developer.android.com/reference/android/app/Fragment.html#onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle))

**Comment by vsay01** [comment]
@florina-muntenescu thanks for the info. it would be useful if you could give example or scenario where it become useful.
I found this and it might useful for others : https://stackoverflow.com/questions/11531648/what-is-the-use-case-for-a-fragment-with-no-ui
