### ISSUE TITLE
[all] Use Google Tasks API instead of repository callbacks

### ISSUE THREAD

**Issue by jpventura** [googlesamples/android-architecture#398]
[Tasks API](https://developers.google.com/android/guides/tasks), which is similar to [Bolts Framework](http://blog.parse.com/learn/introducing-bolts-for-parse-sdks/), brings the concept of [Promises](https://br.udacity.com/course/javascript-promises--ud898/) to Android.

This allow the elimination of the [callback/listener hell](http://callbackhell.com/), writing cleaner code such as:

     mTasksRepository.getTasks()
        .continueWith(FilterOverdue())
        .continueWith(DoSomethingInteresting())
        .continueWith(AnotherInterestingThing())
        .addOnFailureListener(this)
        .addOnSuccessListener(this);

Since is provided by Google Services, wouldn't be interesting replace listeners, callbacks and AsyncTasks by Tasks API?

The major drawback is the name collision, so everything that make references to `Task` would have to be previously renamed to `Ticket` or something else.

**Comment by JoseAlcerreca** [comment]
It would be interesting indeed, but I'm not sure the ToDo app is going to be a good showcase for this API, as we do simple calls.
