### ISSUE TITLE
[todo-mvvm-databinding] How bind items with RecyclerView and it's benefits?

### ISSUE THREAD

**Issue by VictorFernandes** [googlesamples/android-architecture#404]
I'm writing an app based on todo-mvvm-databinding blueprint. But in my app I use RecyclerView instead of ListView. 

```
@BindingAdapter("app:items")
public static void setItems(ListView listView, List<Task> items) {
  TasksFragment.TasksAdapter adapter = (TasksFragment.TasksAdapter) listView.getAdapter();
  if (adapter != null) {
          adapter.replaceData(items);
   }
}
```

I've check the sample and the above code makes the ListView bindable but it on replaceData of the Adapter it always call notifyDataSetChanged. 

For an  RecyclerView.Adapter how can we call notifyItemInserted, notifyItemRangeInserted, etc...?

**Comment by JoseAlcerreca** [comment]
Not related to samples, please post on stackoverflow.
