### ISSUE TITLE
[QUESTION] LiveData Manipulation in ViewModel

### ISSUE THREAD

**Issue by dgngulcan** [googlesamples/android-architecture#408]
I wonder how can I implement @florina-muntenescu's UiModels([here](https://medium.com/upday-devs/mvvm-its-all-in-the-implementation-details-40ed24871a02)) with the architecture provided in [GithubBrowserSample](https://github.com/googlesamples/android-architecture-components/tree/178fe541643adb122d2a8925cf61a21950a4611c/GithubBrowserSample).

For instance, in [UserViewModel.java](https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/ui/user/UserViewModel.java), 
 
```
LiveData<Resource<List<Repo>>> getRepositories() {
        return repositories;
}
```

Instead of returning `LiveData<Resource<List<Repo>>>`, I would like to return a list of UiModels. Thus, I need to manipulate `LiveData<Resource<List<Repo>>>` that is returned from [loadRepos()](https://github.com/googlesamples/android-architecture-components/blob/178fe541643adb122d2a8925cf61a21950a4611c/GithubBrowserSample/app/src/main/java/com/android/example/github/repository/RepoRepository.java#L74) inside the `ViewModel` since it is a UI logic, yet can not observe `LiveData` in the `ViewModel`.

How can I achieve this elegantly?

**Comment by JoseAlcerreca** [comment]
Please post these questions on stackoverflow.
