### ISSUE TITLE
[todo-mvvm-databinding] Context object inside ViewModel?

### ISSUE THREAD

**Issue by eric-grab** [googlesamples/android-architecture#413]
Is it possible to remove to not reference a Context object inside a ViewModel at all? Examples are the **TaskDetailViewModel**, **TaskItemViewModel**, **AddEditTaskViewModel** and **StatisticsViewModel**

**Comment by florina-muntenescu** [comment]
Check out [this sample](https://github.com/googlesamples/android-architecture-components/tree/master/GithubBrowserSample) and classes like [RepoViewModel](https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/ui/repo/RepoViewModel.java).

**Comment by eric-grab** [comment]
Thanks @florina-muntenescu but that's the new Architecture Components (which I don't when they will be out of beta)

Can we achieve 0 context in a plain simple Android MVVM?

**Comment by florina-muntenescu** [comment]
Sure. Just create wrapper classes for different elements. Check out this [ViewModel](https://github.com/florina-muntenescu/android-architecture/blob/dev-todo-mvvm-rxjava/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/statistics/StatisticsViewModel.java) and the [ResourceProvider](https://github.com/florina-muntenescu/android-architecture/blob/dev-todo-mvvm-rxjava/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/util/providers/BaseResourceProvider.java)

**Comment by Apisov** [comment]
@florina-muntenescu Can I ask why the examples use Context in ViewModels? 
I've noticed a lot of suppressions to static field link that smell a little bit hacky.

They use context only for getting String, Drawable resources.
It's clear that we can do it inside of XML via Databinding.

Was is it for the simplicity of the examples? 
Just curious, maybe there is a reason.

**Comment by JoseAlcerreca** [comment]
Yes, it was for simplicity but it's not a huge deal. It's never going to cause a leak. However I recommend you to use data binding for that.

**Comment by Apisov** [comment]
Thanks for the answer.

I saw that it uses application context and it shouldn't leak but all those highlights from Lint make me nervous :)

Maybe we need a special annotation as @ApplicationContext for the fields or more 'flexible' Lint. Although 'suppression' does its work fine.
