### ISSUE TITLE
todo-clean consider use several UseCaseScheduler

### ISSUE THREAD

**Issue by ronenSabagGett** [googlesamples/android-architecture#417]
Currently UseCaseHandler get  UseCaseScheduler in the constructor, if we change it to execute we can provide different implementations, one of them could SynchronousUseCaseScheduler the advantage of it is that we can do some simple tasks such as validation of phone number in the UI thread (it's very cheap check in runtime) but yet we have a great testability and common why to do business logic. The disadvantage is that the caller to the use case must choose in which  UseCaseScheduler to use

**Comment by JoseAlcerreca** [comment]
We'll take it into account if we revisit mvp-clean. Thanks!
