### ISSUE TITLE
Why Activity use Presenter class wheras Fragment use Contact.Presenter

### ISSUE THREAD

**Issue by sattha** [googlesamples/android-architecture#418]
As, title said... why Activity use Presenter class whereas Fragment use Contact.Presenter

**Comment by JoseAlcerreca** [comment]
No real reason. Presenters don't need the interface.

**Comment by sattha** [comment]
@.@ so, no reason..

**Comment by sattha** [comment]
@JoseAlcerreca so, why both activity and fragment use concrete class instead ? why need to use both?  is there any related to Dagger?

**Comment by digitalbuddha** [comment]
Its not related to Dagger and was more us showing different ways to inject something.  Sometimes you have an implementation that is provided directly, other times you are injecting an interface that has a provides/binds method that shows where to get the implementation. We tried to show both types of injections within the blueprints.
