### ISSUE TITLE
[todo-mvp-dagger] DaggerAppComponent class is missing

### ISSUE THREAD

**Issue by akhatriST** [googlesamples/android-architecture#419]
There is no DaggerAppComponent class in package `com.example.android.architecture.blueprints.todoapp.di `, I am getting a compile time error in `ToDoApplication` class in `applicationInjector()` method. 

Am I missing something here. Thanks in advance :)

**Comment by digitalbuddha** [comment]
DaggerAppComponent should get generated when you compile the application. Could you post any errors your are getting when compiling?

**Comment by akhatriST** [comment]
Thanks, compiling resolved the issue. Actually I am using Dagger for the first time, that's why didn't know that it would auto generate on compiling.
