### ISSUE TITLE
using addPresenter instead of setPresenter

### ISSUE THREAD

**Issue by JeremyHe-cn** [googlesamples/android-architecture#42]
In some case, one view need more than one presenter to accomplish business.
So I always change the code like..

View
```java
private FirstPresenter mFirstPresenter;
private SecondPresenter mSecondPresenter;

public void addPresenter(Presenter presenter) {
    if (presenter instanceof FirstPresenter ) {
        mFirstPresenter = (FirstPresenter) presenter;
    }

    if (presenter instanceof SecondPresenter ) {
        mSecondPresenter = (SecondPresenter) presenter;
    }
}
```

**Comment by malmstein** [comment]
I disagree with this statement, a `View` should not have more than one `Presenter`. If that's the case, it usually means that the `View` is responsible for many things and it should be split into smaller components.

**Comment by malmstein** [comment]
To rephrase this better, in the example we are building here that case should never happen and if it does it mean we're over complicating things too much.

**Comment by flipper83** [comment]
I agree with @malmstein addPresener is not necessary in the project right now, addPresenter would be a  premature optimization for our design. Design must growth with our features, we are creating a sample project not a library.

If you need have more than one presenter for you architecture addPresenter could be a good solution.

**Comment by freewheelnat** [comment]
Thanks @JeremyHe-cn ! That may indeed be a good solution if needed, but as @malmstein and @flipper83 said, it's not required for our sample at the moment.
