### ISSUE TITLE
Where is the .ext for rootProject?

### ISSUE THREAD

**Issue by jayakrishnan1236** [googlesamples/android-architecture#427]
```
buildscript {
...
}
ext {
    // Sdk and tools
    minSdkVersion = 10
    targetSdkVersion = 25
    compileSdkVersion = 25
    buildToolsVersion = '25.0.0'

    // App dependencies
    supportLibraryVersion = '25.3.1'
    guavaVersion = '18.0'
    junitVersion = '4.12'
    mockitoVersion = '1.10.19'
    powerMockito = '1.6.2'
    hamcrestVersion = '1.3'
    runnerVersion = '0.5'
    rulesVersion = '0.5'
    espressoVersion = '2.2.2'
}
```
To access the `ext` declared in `Projects` `build.gradle` from `app modules` `build.gradle`  we using `.ext.runnerVersion` to access runnerVersion.
https://github.com/googlesamples/android-architecture/blob/53dc9439a73546bd00e4082f99bc4e9208c9542a/todoapp/app/build.gradle#L80

but while accessing `supportLibraryVersion` which is at the same place why are we directly  accessing it by `rootProject.supportLibraryVersion` and why not `rootProject.ext.supportLibraryVersion`.

https://github.com/googlesamples/android-architecture/blob/53dc9439a73546bd00e4082f99bc4e9208c9542a/todoapp/app/build.gradle#L95

**Comment by JoseAlcerreca** [comment]
I don't understand the question. You don't need ext.

**Comment by oldergod** [comment]
https://stackoverflow.com/a/21700818/1004274
