### ISSUE TITLE
[all] Add UI test + implementation to check recreation of Activity restores state properly.

### ISSUE THREAD

**Issue by Kisty** [googlesamples/android-architecture#428]
Would it be possible to add a UI test which checks that if the activity is exercised in some scenarios, then destroyed by the system, then recreated, it handles that properly? The reasons I raise this is because: 

1. This is a problem I've encountered time and time again without such architectures and manually handling them is a pain.
1. I'm not completely sure how to make a UI test like this. Would it be by using Robolectric or instrumented tests? Would it be by physically doing it or by simulating it? I'm not sure this is possible in an instrumented test.
2. I'm not sure and it isn't documented where the recommended place for managing, storing and restoring view state should live. I think with MVP, for example, I think it should go in the Model layer but having some best practice on how to go about this would be helpful.
3. Would be a good stress test for any application.

Be good to hear your thoughts on this!

**Comment by JoseAlcerreca** [comment]
We do that with the rotation tests in Espresso. Doesn't cover all scenarios of course.

It's a question for Stackoverflow.
