### ISSUE TITLE
[question] todo-mvvm-live-kotlin: Is using ObservableField in ViewModel a good practice?

### ISSUE THREAD

**Issue by savjolovs** [googlesamples/android-architecture#429]
I noticed that in this sample observable fields (ObservableBoolean, ObservableField etc) are placed in ViewModel and ViewModel is passed to the Binding.
It's convenient because the state could be managed in easier way and all the data is in one place.
But I read a few comments hat you shouldn't mix LiveData and ObservableFields. In Android Arch Components Google Sample [GithubBrowserSample](https://github.com/googlesamples/android-architecture-components/tree/master/GithubBrowserSample) you can notice that keeping state and data in ViewModel is replaced by LiveData that returns Resource object which wraps state and data. 
Which way is preferable and what are pros and cons of both?

I also asked this [question on StackOverflow](https://stackoverflow.com/questions/46696170/best-practices-and-patterns-in-viewmodel-data-binding-is-observablefield-in-v)

**Comment by JoseAlcerreca** [comment]
:+1: SO is much better for these questions.
