### ISSUE TITLE
Gradle sync failed: This Gradle plugin requires Studio 3.0 minimum

### ISSUE THREAD

**Issue by dante8300** [googlesamples/android-architecture#430]
Hi i cloned the project  and while looking the samples found that the todo-mvp-rxjava shows this :
**Gradle sync failed: This Gradle plugin requires Studio 3.0 minimum**
 I have Android studio 2.3.3  what would be the best course of action to a successful gradle build in Android Studio?  do i need a beta version of AS to make this work? 
Maybe other people  are facing the same issue, i tried to  use 
'com.android.tools.build:gradle:3.0.0-beta7'   but still not working.

>gradle -v

------------------------------------------------------------
Gradle 2.14.1
------------------------------------------------------------

Build time:   2016-07-18 06:38:37 UTC
Revision:     d9e2113d9fb05a5caabba61798bdb8dfdca83719

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Windows 10 10.0 amd64

Thanks in advance

**Comment by florina-muntenescu** [comment]
Yes, you need to use Android Studio 3.0.
