### ISSUE TITLE
Replace LifecycleAppCompatActivity with AppCompatActivity

### ISSUE THREAD

**Issue by otw** [googlesamples/android-architecture#431]
Branch/sample: "dev-todo-mvvm-live"

Update architecture components version to 1.0.0 and replace LifecycleAppCompatActivity with AppCompatActivity. LifecycleRegistryOwner is now [deprecated](https://developer.android.com/reference/android/arch/lifecycle/LifecycleRegistryOwner.html) and can be used directly through AppCompatActivity.

**Comment by JoseAlcerreca** [comment]
Done in https://github.com/googlesamples/android-architecture/commit/6419d4c523b67d020120fc400ed5a7372e5615f2
