### ISSUE TITLE
Why `deprecated-todo-databinding` deprecated ?

### ISSUE THREAD

**Issue by takahirom** [googlesamples/android-architecture#435]
I'd like you to write it in the README.

**Comment by takahirom** [comment]
Sorry 🙇 
I found it in master branch README
![image](https://user-images.githubusercontent.com/1386930/31582534-0f32031e-b1c1-11e7-87c0-b273871f91c0.png)

**Comment by ZhehaiGit** [comment]
Ok. Got it. Thanks for notice.



‌
