### ISSUE TITLE
New Sample : MVP using Blade and Dagger2

### ISSUE THREAD

**Issue by FrantisekGazo** [googlesamples/android-architecture#441]
I'd like to create a sample that demonstrates the usage of library [Blade](https://github.com/FrantisekGazo/Blade).

**Blade** offers multiple modules for boilerplate destruction, one of which is **mvp** module that makes MVP on Android simple and uses Dagger2 for Presenter injection.

I would also use RxJava2 in the sample.

**Comment by JoseAlcerreca** [comment]
Feel free to create the sample and let us know.
