### ISSUE TITLE
[todo-mvp-rxjava] Refactor to RxJava 2.0

### ISSUE THREAD

**Issue by jpventura** [googlesamples/android-architecture#443]
I have a lot of questions about how to create an new app inspered on [`todo-mvp-rxjava`](https://github.com/googlesamples/android-architecture/tree/todo-mvp-clean), specially regarding [`androidTest`](https://github.com/googlesamples/android-architecture/tree/todo-mvp-clean/todoapp/app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp) and [`test`](https://github.com/googlesamples/android-architecture/tree/todo-mvp-clean/todoapp/app/src/test/java/com/example/android/architecture/blueprints/todoapp).

In RxJava 2.0, [Schedulers.immediate](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#schedulers) was deprecated and it is recommended to use [`TestScheduler`](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#schedulers) instead. However it is not clear to me how to refactor [Android Arch](https://github.com/googlesamples/android-architecture) testing modules.

@florina-muntenescu, do you think it would be worth refactoring this branch to latest RxAndroid/RxJava libraries?

**Comment by florina-muntenescu** [comment]
[todo-mvp-rxjava](https://github.com/googlesamples/android-architecture/tree/todo-mvp-rxjava) already uses RxJava 2. For testing [this](https://github.com/googlesamples/android-architecture/blob/todo-mvp-rxjava/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/util/schedulers/ImmediateSchedulerProvider.java) is used.
Check out the tests from there.
