### ISSUE TITLE
(todo-mvp-kotlin) dependency injection with Koin

### ISSUE THREAD

**Issue by arnaudgiuliani** [googlesamples/android-architecture#445]
Hello,

I work on [Koin](https://github.com/Ekito/koin)  - a Kotlin dependency injection framework that make DI very easy. I made a dedicated branch, from MVP-Dagger & MVP-Kotlin:
https://github.com/Ekito/android-architecture/tree/dev-todo-mvp-kotlin-koin

You can read my article on https://medium.com/@giuliani.arnaud/moving-from-dagger-to-koin-simplify-your-android-development-e8c61d80cddb

Don't know if it can interest you. Let me know :)

**Comment by JoseAlcerreca** [comment]
Hi Arnaud,

It looks interesting! If your framework gets community traction we'll add it to the main list. 

In your article you say 

> The Dagger project has been written by Google team

That's actually not true. Those are written by experts from the community.

It's very cool to see Blueprints used this way, nice job!

**Comment by arnaudgiuliani** [comment]
Hi Jose,

Very cool! We will see if people begin to use Koin. I fixed my article, thanks.

Blueprints are a great reference! 👍

**Comment by kazijosh** [comment]
Hi guys,

Maybe this is not the appropriate issue for this but... I'm a mid-level android dev and I'm starting to use MVP so I was wondering, what are the benefits of creating a Fragment and Activity for every screen? Does it have to do with Activity lifecycles?

Sorry for polluting this @arnaudgiuliani

**Comment by JoseAlcerreca** [comment]
@kazijosh indeed not the place for that question. Google it or try Stackoverflow to read about the pros and cons of each solution.

We mention it in the todo-mvp readme 

> The use of both activities and fragments allows for a better separation of concerns which complements this implementation of MVP. In this version of the app, the Activity is the overall controller which creates and connects views and presenters.
