### ISSUE TITLE
Adding a kotlin example of existing architecture samples

### ISSUE THREAD

**Issue by worstkiller** [googlesamples/android-architecture#457]
Hi team, I would like to contribute to  android-architecture for Kotlin version of the existing samples. I would like to know how I can and where I can push those changes if possible.
Thanks

**Comment by florina-muntenescu** [comment]
We have a [contributing](https://github.com/googlesamples/android-architecture/blob/master/CONTRIBUTING.md) page. Check it out and then create issues based on what you want to do.
