### ISSUE TITLE
New Sample : Functional Programming architecture using KΛTEGORY

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [googlesamples/android-architecture#461]
Since 7 months ago, we have been working on a functional programming library called [KΛTEGORY](http://kategory.io/). It brings functional data types and abstractions over Kotlin, and it's open to integrations with different platforms and libraries. We are moving very fast towards a first stable release, and we are actually very close to it. Already completing last steps on documentation and so on.

We have been talking about it on events like Mobilization Poland or Kotlinconf.

KΛTEGORY is a paradigm enabling library, so it could be a framework by itself. You can write any platform related apps or systems with it, as long as Kotlin is supported on the platform.

We would love to provide an architecture sample using it, the very first sample showcasing a different paradigm, similar to what you can already find on [this sample repo](https://github.com/JorgeCastilloPrz/KotlinAndroidFunctional). 

Our idea over this is to provide a base implementation and iterate over it, so we would like to end up working on integrations with some "community wide accepted" Google libs like Architecture Components and Room. This could lead to very interesting collaborations! :)

You can have a look to the integration we have for RxJava2 (please look at `kategory-effects-rx2` module) as an example.

Thanks in advance!

The KΛTEGORY team.

**Comment by JoseAlcerreca** [comment]
Feel free to create the sample based on one of the branches and let us know.

**Comment by JorgeCastilloPrz** [comment]
Will do. Thanks!

**Comment by JorgeCastilloPrz** [comment]
One question. Should we fork and open a PR to you guys with the sample or do you want us to provide it as a completely separate repo to just link to it under the external samples? @JoseAlcerreca

**Comment by JoseAlcerreca** [comment]
Separate repo. We only add external samples if they're about an relevant pattern or they use a library commonly used by the community. 

I suggest you use blueprints to show how to migrate from todo-mvp to your lib. Like https://android.jlelse.eu/moving-from-dagger-to-koin-simplify-your-android-development-e8c61d80cddb

**Comment by JorgeCastilloPrz** [comment]
Ok, thanks.
