### ISSUE TITLE
Any advice to integrate Facebook Single Sign On to this architecture?

### ISSUE THREAD

**Issue by IHNEL** [googlesamples/android-architecture#462]
I understand and are using this architecture in my currently project. Now I want to integrate a feature that request Facebook SDK to execute login.

Im my opinion, Facebook SDK acts as a Data-Provider (which provide authentication service) and should be setup and using under `data` module instead of `app` module. For example if I want to execute Facebook Login, I will invoke appropriate use-case, then such use-case will call `data` module to do actual work.

But, the challenge is Facebook method (see Facebook's LoginManager, [Here](https://developers.facebook.com/docs/facebook-login/android/) ), require Activity/Fragment instance to run.

So, should I move Facebook SDK back to `app`module or pass the Activity instance down to `storage` module?

I don't really like any options of them. (felling not happy although it helps to resolve requirement). Does anyone have any better approach?
Thanks

**Comment by florina-muntenescu** [comment]
This is a stackoverflow question. Feel free to post your question there.
