### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by clivejefferies** [googlesamples/android-architecture#465]
https://github.com/googlesamples/android-architecture/blob/30f7c5a16bb0854e003530e81403e922e745d311/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksPresenter.java#L49

Would having a reference to a context (in this case the fragment) cause a memory leak?

**Comment by JoseAlcerreca** [comment]
It's risky and you need to know what you're doing, but no. The presenter dies with the activity, a new one is created on config change. There could be temporary leaks if the presenter is waiting for an operation to complete, but that's it.

**Comment by clivejefferies** [comment]
OK, cool, what about if fragments were not used and the view was an activity?

On 22 Nov 2017 14:57, Jose Alcérreca <notifications@github.com> wrote:

It's risky and you need to know what you're doing, but no. The presenter dies with the activity, a new one is created on config change. There could be temporary leaks if the presenter is waiting for an operation to complete, but that's it.
