### ISSUE TITLE
Add instructions on how to open projects in Android Studio

### ISSUE THREAD

**Issue by wzyzb** [googlesamples/android-architecture#47]
how to import this to android studio?

**Comment by JoseAlcerreca** [comment]
git checkout todo-mvp ?

**Comment by malmstein** [comment]
you'll need to checkout one of the branches and open the root `build.gradle` file from Android Studio

**Comment by malmstein** [comment]
fixed https://github.com/googlesamples/android-architecture/pull/60

**Comment by highdali** [comment]
how do import...?
