### ISSUE TITLE
MVP with multiple fragments

### ISSUE THREAD

**Issue by cfva14** [googlesamples/android-architecture#470]
How do you handle multiple fragments in a single activity? Example, steps for registering a new user in a login Activity.
Because currently we need the fragment for the presenter, but what happens when you have multiple fragments?

**Comment by franciscodjosh** [comment]
One way of doing this is to have all the registration fragments depend on the same presenter:
In your LoginActivity you would have instances of the fragments that you want to show in every step of the registration process and you would create a method like **showFragment(String fragmentId)** in this activity. That method just replaces a fragment with another.

Then on LoginActivity's onCreate method, you would pass the instance of the activity to the presenter and also the fragment instances. That way the presenter will have access to the **showFragment(String fragmentId)** (so you can swap your fragments) and still control the behaviour of those fragments.

But keep in mind that this solution is practical when you don't have a lot of logic to handle in each fragment. If you do, I recommend using several presenters to keep the separation of concerns and make your code easier to maintain.

**Comment by florina-muntenescu** [comment]
Feel free to move this discussion on stackoverflow for traceability.
