### ISSUE TITLE
Private property in Task entity "Cannot find getter"

### ISSUE THREAD

**Issue by iraj-wisilica** [googlesamples/android-architecture#473]
I get "Cannot find getter" for the fields with the following libraries.

annotationProcessor "android.arch.persistence.room:compiler:1.0.0"
implementation 'android.arch.persistence.room:runtime:1.0.0'

When I changed the Entity properties to public everything worked. What is the relevance of private & public properties for Entities annotated with @Entity.

**Comment by iraj-wisilica** [comment]
What is the relevance of private & public properties for Entities annotated with @entity.?

**Comment by florina-muntenescu** [comment]
Entities need to have getters for private members. 
Check out the [documentation](https://developer.android.com/training/data-storage/room/defining-data.html) for details.

**Comment by iraj-wisilica** [comment]
@florina-muntenescu Thanks for the info.

**Comment by chamakov** [comment]
@iraj-wisilica i used to have the same problem, i just rename the variable and it works, i don't know why, but it works

**Comment by Eipeks** [comment]
Worked here too. I have absolutely no idea why.

**Comment by samirsamedow** [comment]
> Entities need to have getters for private members.
> Check out the [documentation](https://developer.android.com/training/data-storage/room/defining-data.html) for details.

Good point, but private or public. ever field in documantation is public

**Comment by emretekin** [comment]
I exactly faced with same issue and It works another computer but not in mine. 
So weird. According to @chamakov  and @iraj-wisilica  responses, I tried change the name from "id" to "workerId" and it works. WEIRD!
