### ISSUE TITLE
Can not clone the code by git clone

### ISSUE THREAD

**Issue by abneryan** [googlesamples/android-architecture#474]
Under the url  :https://github.com/googlesamples/android-architecture/tree/todo-mvp/

**Comment by JairAviles** [comment]
You need to clone from master branch using the URL (HTTPS): https://github.com/googlesamples/android-architecture.git

If you want to fetch the todo-mvp branch, you just need to run after cloning from master the following command `git fetch && git checkout todo-mvp`
