### ISSUE TITLE
[todo-mvp-rxjava] need guidance on how implement Firebase as the remote datasource

### ISSUE THREAD

**Issue by andrewclam1991** [googlesamples/android-architecture#476]
I'm a newbie in RxJava and the MVP structure in general. I have more experience using Firebase RTDB the traditional way and now I'm wondering how to best adapt it as a RemoteDataSource (ex TaskRemoteDataSource). In the other MVP examples I would just use callback.onTaskLoaded(task), but with the example contract requiring a return of a Flowable<T>. 

Coming from the callback-world of Firebase query and writes. I'm wondering what is the best practice for handling Firebase callback with RxJava. Upon searching github there are N RxFirebase libraries that seems to work but I'm not sure which one to couple my project with. Thank you.

**Comment by JoseAlcerreca** [comment]
Try stackoverflow for this type of question.
