### ISSUE TITLE
How to use SingleLiveEvent

### ISSUE THREAD

**Issue by Deep21** [googlesamples/android-architecture#480]
Hi all,
I'am trying to implement the SingleLiveEvent but I can't figure it out.
Here the ContactViewModel:
`private SingleLiveEvent<Integer> contactId = new SingleLiveEvent<>();`
`private MutableLiveData<Resource<Contact>> data = new MediatorLiveData<>();`
`private MediatorLiveData<Resource> contactsListMediatorLiveData;`

 `public MediatorLiveData<Resource> getContactById() {`
  ` if (tMediatorLiveDatas == null) {`
    ` tMediatorLiveDatas = new MediatorLiveData<>();`
     `tMediatorLiveDatas.addSource(contactId, this::loadContactById);`
     `tMediatorLiveDatas.addSource(data, resource -> tMediatorLiveDatas.setValue(resource));`
     `tMediatorLiveDatas.addSource(error, resource -> tMediatorLiveDatas.setValue(resource));`
   `}`
  `Log.d(TAG, "getContactById: e");`
  `return tMediatorLiveDatas;`
`}`

`public void loadContactById(int id) {`
  `Log.d(TAG, "loadContactById: " + id);`
  `invoiceRepo.getContact(id).subscribe(`
     `s -> data.setValue(Resource.success(s)),`
     `throwable -> error.setValue(Resource.error(throwable.getMessage(), throwable)));`
`}`

https://github.com/Deep21/LifeCycleAware/blob/switchMap/app/src/main/java/com/example/samfisher/lifecycleaware/ContactViewModel.java

In the MainActivity when the user click on an item I set the value of the contact id:

`@Override`
  `protected void onCreate(Bundle savedInstanceState) {`
    `AndroidInjection.inject(this);`
    `super.onCreate(savedInstanceState);`
   `setContentView(R.layout.activity_main);`
    `ButterKnife.bind(this);`
    `fab.setOnClickListener(v -> model.loadContact());`
    `contactListAdapter.setOnItemClickListener(position -> {model.setContactId(position);`
  `});`
  `recyclerView.setHasFixedSize(true);`
  `LinearLayoutManager mLayoutManager = new LinearLayoutManager(this);`
  `recyclerView.setLayoutManager(mLayoutManager);`
  `recyclerView.setAdapter(contactListAdapter);`
 `model = ViewModelProviders.of(this,viewModelFactory).get(ContactViewModel.class);`
 `showContacts();`
  `observeOnContactSelected()`;
 `}`

  `private void observeOnContactSelected() {`
    `model.getContactById().observe(this, resource -> Log.d(TAG, `
   ` "observeOnContactSelected: " + ((Contact)resource.data).getCompany()));`
  `}`

  `private void showContacts() {`
     `model.getContacts().observe(this, resource -> {`
     `Log.d(TAG, "onCreate: " + resource);`
     `contactListAdapter.setContactList((List<Contact>) resource.data);`
     `contactListAdapter.notifyDataSetChanged();`
  `});`
  `}`
`}`

https://github.com/Deep21/LifeCycleAware/blob/switchMap/app/src/main/java/com/example/samfisher/lifecycleaware/MainActivity.java

I can't figure out how to use the SingleLiveEvent, when the device rotate I still got the old value from observeOnContactSelected() method, can someone help me please? 

Thank you

**Comment by JoseAlcerreca** [comment]
This is question for Stackoverflow.
