### ISSUE TITLE
New sample: Kotlin MVI with dagger and RxJAva

### ISSUE THREAD

**Issue by arranlomas** [googlesamples/android-architecture#481]
I plan on making an example of the TODO app as a proposal to use this architecture in my organization. It will be using mvi, kotlin, dagger and RxJava, I am also working on a series of articles to accompany. This is heavily influenced by the Java MVI sample. However, now kotlin is a 1st party language, a think a sample of this architecture would be useful as this architecture lends itself very well to this architecture. 

You can see the start of this work [here](https://github.com/arranlomas/kontent)

**Comment by oldergod** [comment]
btw, the `todo-mvi-rxjava` will be rewritten in Kotlin before the [DroidKaigi](https://droidkaigi.jp/2018/) conference.

**Comment by arranlomas** [comment]
Great! I'll keep track of that, I'll still proceed with my implementation as an experiment to see it through and I can compare what I end up with to the re-written implementation. Thanks for your work! It's been a great help! Especially your talk at droidcon NYC! It was the final piece in the puzzle for me. If you need any contributors I'd love to help.

**Comment by arranlomas** [comment]
@oldergod I was wondering how this was going? I particularly wanted discuss the way you filter the Initial intent. 

In the base component I have been using I have come up with a solution that doesn't require having the GetLastState objects in the intents, action results etc.

There is a really small pull request outlining how these changes could be implemented in a base class:
https://github.com/arranlomas/kontent/pull/2/files

I would love you to take a look and get your thoughts on this, if you think this may offer a cleaner solution. Thanks!

**Comment by oldergod** [comment]
We can discuss about it in the repo here https://github.com/oldergod/android-architecture
It is now written in Kotlin, and the `GetLastState` thing is not used anymore.

**Comment by arranlomas** [comment]
Great work! I will add any comments there in the future. I much prefer the method your using there of composing the intent filter and shared.notOfType
