### ISSUE TITLE
[todo-mvp-rxjava] tasks do not persist across app-restart

### ISSUE THREAD

**Issue by andrewclam1991** [googlesamples/android-architecture#482]
After adding a task, on rotation the tasks are persisted, but when app restarts they will be gone. By design, the task should persist.

It seems to have something to do with how the remote data source sync is implemented in the example? (force refresh). Remote data source could be empty and the refresh would only expose the remote data stream to subscriber down stream.

        if (mCacheIsDirty) { // note this flag will always be true on app restart or on rotation
            return remoteTasks;
        } else {
            // Query the local storage if available. If not, query the network.
            Flowable<List<Task>> localTasks = getAndCacheLocalTasks();
            return Flowable.concat(localTasks, remoteTasks)
                    .filter(tasks -> !tasks.isEmpty())
                    .firstOrError()
                    .toFlowable();
        }

and remoteTasks is returned from this method, getAndSaveRemoteTasks()

    private Flowable<List<Task>> getAndSaveRemoteTasks() {
        return mTasksRemoteDataSource
                .getTasks()
                .flatMap(tasks -> Flowable.fromIterable(tasks).doOnNext(task -> {
                    mTasksLocalDataSource.saveTask(task);
                    mCachedTasks.put(task.getId(), task);
                }).toList().toFlowable())
                .doOnComplete(() -> mCacheIsDirty = false); 
    }

I'm speculating the Task only persisted upon screen rotation because it is written in-memory remote datasource, once the app is completely exit, the datasource is gone in remote, but it still exists in the local db. The local db is never queried because of the cache flag is set to false upon restart. Any good idea on how to fix this?

**Comment by JoseAlcerreca** [comment]
#123
