### ISSUE TITLE
[todo-mvp-clean] run parallels useCases -> changed requestValues of pending useCases

### ISSUE THREAD

**Issue by thaihuynhxyz** [googlesamples/android-architecture#488]
I put 
`protected void executeUseCase(final RequestValues values) {`
`Log.e("qwerty", "executeUseCase completedTask =" + values.getCompletedTask());`
`Thread.sleep(TimeUnit.SECONDS.toMillis(10));`
`...`
`}`
 in CompleteTask.executeUseCase

and
`public void completeTask(@NonNull Task completedTask) {`
`Log.d("qwerty", "completeTask: completedTask = " + completedTask.getId());`
`...`
`}`
in TasksPresenter.completeTask

so I get logs as below:
01-08 17:44:21.195 5449-5449/com.example.android.architecture.blueprints.todomvpclean.mock D/qwerty: completeTask: completedTask = b17b23e3-1435-4bfb-8448-5e35ea2ef12b
01-08 17:44:21.197 5449-5484/com.example.android.architecture.blueprints.todomvpclean.mock E/qwerty: executeUseCase completedTask =b17b23e3-1435-4bfb-8448-5e35ea2ef12b
01-08 17:44:21.542 5449-5449/com.example.android.architecture.blueprints.todomvpclean.mock D/qwerty: completeTask: completedTask = 89d2c01c-f187-47e9-a99d-120991476f68
01-08 17:44:21.542 5449-5468/com.example.android.architecture.blueprints.todomvpclean.mock E/qwerty: executeUseCase completedTask =89d2c01c-f187-47e9-a99d-120991476f68
01-08 17:44:22.065 5449-5449/com.example.android.architecture.blueprints.todomvpclean.mock D/qwerty: completeTask: completedTask = 664d6809-0917-4e50-949c-6faef1267804
01-08 17:44:22.634 5449-5449/com.example.android.architecture.blueprints.todomvpclean.mock D/qwerty: completeTask: completedTask = de9a7109-122e-46de-ba9e-6aece5c17526
01-08 17:44:23.140 5449-5449/com.example.android.architecture.blueprints.todomvpclean.mock D/qwerty: completeTask: completedTask = c7269e9b-6cdd-4027-b693-b52c721a5af3
01-08 17:44:23.141 5449-5504/com.example.android.architecture.blueprints.todomvpclean.mock E/qwerty: executeUseCase completedTask =c7269e9b-6cdd-4027-b693-b52c721a5af3
01-08 17:44:23.715 5449-5449/com.example.android.architecture.blueprints.todomvpclean.mock D/qwerty: completeTask: completedTask = 6c8bd4cd-f965-45ab-bf34-cdb430913836
01-08 17:44:23.716 5449-5505/com.example.android.architecture.blueprints.todomvpclean.mock E/qwerty: executeUseCase completedTask =6c8bd4cd-f965-45ab-bf34-cdb430913836
01-08 17:44:31.205 5449-5484/com.example.android.architecture.blueprints.todomvpclean.mock E/qwerty: executeUseCase completedTask =6c8bd4cd-f965-45ab-bf34-cdb430913836
01-08 17:44:31.545 5449-5468/com.example.android.architecture.blueprints.todomvpclean.mock E/qwerty: executeUseCase completedTask =6c8bd4cd-f965-45ab-bf34-cdb430913836

3 last useCases run with same requestValue with completedTask =6c8bd4cd-f965-45ab-bf34-cdb430913836

**Comment by JoseAlcerreca** [comment]
Can you explain what your point is?

**Comment by thaihuynhxyz** [comment]
You need new CompleteTask instance instead use 1 instance then run with new RequestValues. In case UseCase take more time, RequestValues will be replaced by the last.
My above story is. I have 6 task, I put above code to simulate long time Use Case. I complete 6 task but 4 tasks are completed. last 2 UseCase's RequestValues are replaced by the 4th id 6c8bd4cd-f965-45ab-bf34-cdb430913836.
