### ISSUE TITLE
new task - backpress - not saved

### ISSUE THREAD

**Issue by Rainer-Lang** [googlesamples/android-architecture#49]
1) fab: create new task
2) title="Test"
3) backpress
4) return to main-activity without asking, saving or anything else

tested with rxjava-branch

UPDATE:
Should even happen in basic-sample.

**Comment by JoseAlcerreca** [comment]
Yeah this happens in every variant. A real app should ask before exiting, but in this case I think it's fine. It wouldn't impact architecture, it would just be a feature of the views.

**Comment by Rainer-Lang** [comment]
@JoseAlcerreca That's your opinion.
I'm thinking about samples/blueprints/best practices/show cases/... just different. But I think we shouldn't start a discussion about this.

But I respect your decision.

**Comment by JoseAlcerreca** [comment]
Thanks for your understanding!
