### ISSUE TITLE
todo-mvp-dagger- why define same method in each contract as in basepresenter?

### ISSUE THREAD

**Issue by cgomezmendez** [googlesamples/android-architecture#490]
todo-mvp-dagger
(I can't link the line numbers right now cause it won't work in my browser)
In TasksContract.Presenter interface there is the definition of the method dropview, but that interface already implements BasePresenter which have that method, what is the reason to have the same method definition twice?
https://github.com/googlesamples/android-architecture/blob/todo-mvp-dagger/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksContract.java
https://github.com/googlesamples/android-architecture/blob/todo-mvp-dagger/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/BasePresenter.java

**Comment by digitalbuddha** [comment]
no reason was an oversight fixing now
