### ISSUE TITLE
[all] Why LiveData requires UI update callbacks as against Observables

### ISSUE THREAD

**Issue by birender-s** [googlesamples/android-architecture#492]
I need one clarification regarding LiveData usage Vs Observables. When we use observable attribute in ViewModel and reference in layout XML of Fragment/Activity, subsequent updates of observable attribute are auto handled in View (without requiring callback code). Whereas when using LiveData attribute (in place of observable), why do we have to write extra callback handler to update UI in Activity/Fragment class, it "increases boilerplate code". Shouldn’t DataBinding lib handle it internally just like with observables ? Am i missing anything? May be this change is already on the roadmap. Please advise.
Just to make it clear, i am referring to this code when using LiveData:
        // Create the observer which updates the UI.
        final Observer<String> nameObserver = new Observer<String>() {
            @Override
            public void onChanged(@Nullable final String newName) {
                // Update the UI, in this case, a TextView.
                mNameTextView.setText(newName);
            }
        };

**Comment by arun0102** [comment]
Data Binding now supports LiveData as an observable field in data binding expressions. This is recently been added into build tools version 3.1.0-alpha06. See the release notes here.
[https://androidstudio.googleblog.com/2017/12/android-studio-31-canary-6-is-now.html](url)

**Comment by JoseAlcerreca** [comment]
What arun said :)
