### ISSUE TITLE
Error:(14, 8) error: Entities and Pojos must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type). Tried the following constructors but they failed to match: Words(java.lang.String) : [word : null]

### ISSUE THREAD

**Issue by krunal2** [googlesamples/android-architecture#499]
This is my code:-

@Entity(tableName = "Words")
public class Words {

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "wid")
    public int wid;
    @ColumnInfo(name = "Word")
    public String Word;

    public Words(String word){
        this.Word = word;
    }

    public String getWords(){
        return this.Word;
    }
}

here is my dependencies:-

implementation "android.arch.lifecycle:extensions:1.0.0"
    annotationProcessor "android.arch.lifecycle:compiler:1.0.0"

    // Room
    implementation "android.arch.persistence.room:runtime:1.0.0"
    annotationProcessor "android.arch.persistence.room:compiler:1.0.0"

    // Paging
    implementation "android.arch.paging:runtime:1.0.0-alpha4-1"

    // Test helpers for LiveData
    testImplementation "android.arch.core:core-testing:1.0.0"
    implementation "android.arch.lifecycle:common-java8:1.0.0"
    // Test helpers for Room
    testImplementation "android.arch.persistence.room:testing:1.0.0"

    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.android.support:appcompat-v7:26.1.0'

    implementation 'com.android.support.constraint:constraint-layout:1.0.2'

    testImplementation 'junit:junit:4.12'

    androidTestImplementation 'com.android.support.test:runner:1.0.1'

    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    implementation 'com.android.support:design:26.1.0'

**Comment by JoseAlcerreca** [comment]
Please ask in Stackoverflow

**Comment by ooMICAHoo** [comment]
@krunal2 Did you ever figure this out or post in Stackoverflow?

**Comment by ooMICAHoo** [comment]
So I actually think I figured this out, at least I got it to work in my own code 

Modify the parameter name in the constructor to be the same as the column you are associating it with.

So you would go from:
`public Words(String word){
    this.Word = word;
}`

to:
`public Words(String Word){
    this.Word = Word;
}`

The difference for you is just the capitalization of 'word'. 

For Room to be happy, you have to either have an empty constructor or have the parameters exactly match the fields. The Error message actually proved to be very helpful when fully read.
