### ISSUE TITLE
It's not necessary to create Contact Interface to each activity.

### ISSUE THREAD

**Issue by SuperBeagleDog** [googlesamples/android-architecture#501]
Why not create a BaseContact for activities? 
for instance, you may do like this:

public interface AContact{
     void onClickA();
}

public interface BContact{
     void onClickB();
}

Now, the codes may can be simplify to:

public interface BaseContact{
  void onClick(int what);
}

When you use, like this , onClick(A) or onClick(B);

If do so, it may can be reduce many Interfaces files and more easily do.

**Comment by JoseAlcerreca** [comment]
Sure, feel free to go that way.
