### ISSUE TITLE
[todo-mvvm-live] ViewModelFactory memory leak

### ISSUE THREAD

**Issue by enthyp** [googlesamples/android-architecture#509]
I have a newbie question concerning ViewModelFactory and its mApplication field. There is a suppressed warning about memory leak due to Context field in ViewModelFactory class which is referenced statically. So my question is: is it a recommended practice to use such field in ViewModel factory class? And is there actually any memory leaked here?
Thank you. 

I apologize if this question should place elsewhere, e.g. StackOverflow.
Regards,
Jakub

**Comment by JoseAlcerreca** [comment]
No, the only context that is dangerous is an Activity. Yes, stackoverflow would be a better place for these questions.
