### ISSUE TITLE
todo-mvp-dagger: You are using the concrete implementation of StatisticsPresenter instead of StatisticsContract.Presenter

### ISSUE THREAD

**Issue by MikeMitterer** [googlesamples/android-architecture#524]
https://github.com/googlesamples/android-architecture/blob/todo-mvp-dagger/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/statistics/StatisticsActivity.java#L41

**Comment by digitalbuddha** [comment]
Good catch! Want to contribute a pr changing or should I fix it?

**Comment by JoseAlcerreca** [comment]
There's no point in having an interface in the presenter. It's never used.

**Comment by bovink** [comment]
i don't think we can gain any benefit using  StatisticsContract.Presenter here
