### ISSUE TITLE
"Samples at a glance" out of date

### ISSUE THREAD

**Issue by stevesamknows** [googlesamples/android-architecture#540]
Helpful wiki page no longer reflects current state of branches

**Comment by sindyoke** [comment]
It would be really helpful if one of the contributors took some time to update the table with the new and updated architectures. For example, I would like to start with MVVM Databinding Live, but I am not sure how it compares to others.

**Comment by JoseAlcerreca** [comment]
I don't think that section makes sense anymore. Thanks!
