### ISSUE TITLE
dev-todo-mvvm-rxjava: tasks are never saved to local data source when refreshTasks() is called in TasksRepository

### ISSUE THREAD

**Issue by Nimrodda** [googlesamples/android-architecture#543]
I followed the example TasksRepository from `dev-todo-mvvm-rxjava` branch, specifically the refresh method where the response from the server is persisted to the local data source and found out an issue with the code. 

`TasksRepository.refreshTasks()` is chained with `.doOnNext(mTasksLocalDataSource::saveTasks)`. Tasks are never saved to local data source because the observable (Completable in this case) that is returned from  `TasksLocalDataSource.saveTasks(tasks)` is never subscribed.

The issue is that `doOnNext()` doesn't subscribe the observable and should only be used for side effects. Instead you should use `flatMap` or similar operator so that the observable will be subscribed as part of the stream.

**Comment by JoseAlcerreca** [comment]
#123
