### ISSUE TITLE
I want to ask what i can't understand. Appreciate answer.

### ISSUE THREAD

**Issue by linguokunSponia** [googlesamples/android-architecture#549]
Hello @JoseAlcerreca 

In todo‑mvp project, I don't know why the presenter hold the view(activity) reference and call activity's method to update UI rather than pass the callback from activity to presenter and to model and update UI by callback? 

I think this will lead to coupling between Activity and presenter.( and will lead the code become more complex. For example, I will continually switch screen between activity and presenter when I read the project code. It really make me tired)

Why don't let presenter just be the role of mediator which meets the Mediator Pattern and Law of Demeter and Single Responsibility Principle.
I think it is better if presenter keep simple.(just be the mediator between activity and model)

What do you think?Thanks.

**Comment by JoseAlcerreca** [comment]
Instead of one reference to the view, you would have to maintain multiple references to the view (the callbacks).

**Comment by linguokunSponia** [comment]
@JoseAlcerreca 
Thanks your reply, But I can use anonymous inner class to be the method's parameter so these callbacks are not the global variables(they are local variables in method). Are there any problems or not good if I do this?
