### ISSUE TITLE
branch/todo-mvp-dagger,This example is not very comprehensive，I didn't see the use of "module", "component", "scope" and so on. I only saw "@inject".

### ISSUE THREAD

**Issue by Vector-SMG** [googlesamples/android-architecture#554]
/* Remove this comment
Please add the branch/sample ("all", "todo-mvp", "todo-mvp-dagger", etc.) 
in the title if it applies.
*/

**Comment by digitalbuddha** [comment]
This project does contain components modules and Scopes. Here are the top level ones.  https://github.com/googlesamples/android-architecture/tree/todo-mvp-dagger/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/di  additionally this project leverages dagger-Android which auto generates subcomponents for you. Refer here for documentation on how dagger android works https://google.github.io/dagger/android.html

**Comment by Vector-SMG** [comment]
oh,yes.
