### ISSUE TITLE
[todo-mvp-dagger] - help needed in understanding how TasksRepository is getting injected

### ISSUE THREAD

**Issue by vinkrish** [googlesamples/android-architecture#561]
TasksRepository is injected into TasksPresenter and in no module it has been annotated with @ Binds or @Provides.

**Comment by mvescovo** [comment]
I also have this problem and have written a stackoverflow post here: https://stackoverflow.com/questions/50869969/android-architecture-blueprints-todo-mvp-dagger-where-is-provides-for-tasksr

**Comment by drawers** [comment]
This question was probably better suited as a StackOverflow question rather than an issue that required cross-posting, but there is an answer now anyway and the issue can probably be closed:

https://stackoverflow.com/a/50870340/5241933

**Comment by mvescovo** [comment]
@vinkrish ok someone answered the question. Easier to read it than me re-explain it here.
