### ISSUE TITLE
New Sample: MVVM-clean-dagger2-databinding

### ISSUE THREAD

**Issue by AMarinaG** [googlesamples/android-architecture#57]
no examples at mvvm architectures?

**Comment by JoseAlcerreca** [comment]
This sample would be 4 levels deep. We need the MVVM, clean and dagger2 samples first. Closing for now.

**Comment by Rainer-Lang** [comment]
@JoseAlcerreca I suggest to tag this issue as "Community request" and reopen it. Maybe someone wants to make it.

**Comment by AMarinaG** [comment]
@JoseAlcerreca 

Hi , I created the architecture proposed, MVVM dagger2 databingind and retrofit .

Here is the link [MVVM dagger2 retrofit2 databinding - AMarinaG](https://github.com/AMarinaG/sample-mvvm-retrofit-dagger-databinding)

It would be very important if you could take a look and tell me what you think and as I improve .

Thank you!

P.D.- Sorry for my English

**Comment by JoseAlcerreca** [comment]
@AMarinaG Oh, I thought you had implemented our TODO app!

 I'd start by adding tests :)

**Comment by AMarinaG** [comment]
Hi, i applied google styles from [https://github.com/google/styleguide](https://github.com/google/styleguide)

but not applied on layout files, can u said me how i applied our styles? any files? any script?


previously used [https://github.com/square/java-code-styles](https://github.com/square/java-code-styles) , easy way , just run script

sorry for noob question :(

i'll start with todo app mvvm dagger2 databinding...
