### ISSUE TITLE
[todo-mvp-dagger]: Error: cannot find symbol variable DaggerAppComponent

### ISSUE THREAD

**Issue by abhi007tyagi** [googlesamples/android-architecture#570]
I am trying to build an app that is based on [todo-mvp-dagger] and retrofit. After creating the initial classes, modules, room db (first time using) and Rebuilding the project, I am receiving  an **error: cannot find symbol variable DaggerAppComponent** 

The [todo-mvp-dagger] app is building fine but mine is not. What am I missing?
Here is my [project repository](https://github.com/abhi007tyagi/MVP-Dagger2-Retrofit-Room)

Added [StackOverflow](https://stackoverflow.com/questions/51216376/room-retrofit-dagger2-mvp-error-cannot-find-symbol-variable-daggerappcomponent) question as well

**Comment by JoseAlcerreca** [comment]
This should be answered in SO, so I'm closing this.
