### ISSUE TITLE
dev-todo-mvvm SingleLiveEvent incomplete / superficial

### ISSUE THREAD

**Issue by danielesegato** [googlesamples/android-architecture#577]
I'm referring to this class:
https://github.com/googlesamples/android-architecture/blob/dev-todo-mvvm-live/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/SingleLiveEvent.java

And specifically this part:

```
    @MainThread
    public void observe(LifecycleOwner owner, final Observer<T> observer) {

        if (hasActiveObservers()) {
            Log.w(TAG, "Multiple observers registered but only one will be notified of changes.");
        }

        // Observe the internal MutableLiveData
        super.observe(owner, new Observer<T>() {
            @Override
            public void onChanged(@Nullable T t) {
                if (mPending.compareAndSet(true, false)) {
                    observer.onChanged(t);
                }
            }
        });
    }
```

`super.observe()` call pass an Observer that has just been created, this means that any call to `removeObserver()` later passing the original observer will accomplish nothing.

furthermore the `observerForever()` method still works normally.

overall this class doesn't look ready for production

**Comment by JoseAlcerreca** [comment]
obsolete
