### ISSUE TITLE
Use database crash:android.database.sqlite.SQLiteFullException  database or disk is full (code 13)

### ISSUE THREAD

**Issue by haoma2012** [googlesamples/android-architecture#583]
![image](https://user-images.githubusercontent.com/9374689/44637017-64e0f400-a9e1-11e8-96cf-6a20e61413dd.png)
The following phone models occur：

Android 4.4.4,level 19  
ROM：vivo/FUNTOUCH 
CPU：armeabi-v7a

Android 6.0,level 23
ROM：Meizu/FLYME
CPU：arm64-v8a

disk is full?  What causes it？
`

android.database.sqlite.SQLiteConnection.nativeExecuteForString(Native Method)
--
2 android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:656)
3 android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:334)
4 android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:302)
5 android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
6 android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:204)
7 android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
8 android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
9 android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
10 android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:840)
11 android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:825)
12 android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:718)
13 android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:599)
14 android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
15 android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
16 android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
17 android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.a(TbsSdkJava:96)
18 android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.b(TbsSdkJava:54)
19 android.arch.persistence.room.RoomDatabase.h(TbsSdkJava:252)
20 com.meiyou.sheep.main.db.SearchWordDao_Impl.void insert(com.meiyou.sheep.main.model.SearchHistoryDo)(TbsSdkJava:72)
21 **com.meiyou.sheep.main.presenter.SearchResultPresenter.void lambda$insertSearchToTable$0$SearchResultPresenter(java.lang.String)(TbsSdkJava:123)
22 com.meiyou.sheep.main.presenter.SearchResultPresenter$$Lambda$0.void run()(Unknown Source)**
23 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
24 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
25 java.lang.Thread.run(Thread.java:818)

`

**Comment by JoseAlcerreca** [comment]
Try the issue tracker. It's not related to the samples.
