### ISSUE TITLE
todo-mvvm-databinding:  Cannot resolve 'TasksFragBinding' 

### ISSUE THREAD

**Issue by alvindizon** [googlesamples/android-architecture#591]
I checked out the todo-mvvm-databinding branch, and I noticed that the TasksFragment class has a reference to a missing class called TasksFragBinding.

**Comment by lfork** [comment]
Class TasksFragBinding is a auto generated.  
When you built it successfully. You can see the  Class TasksFragBinding.

**Comment by alvindizon** [comment]
@lfork  I see where the problem is now, I upgraded supportLibraryVersion to 28, that's where the problem started, I reverted back to 26.1.0, now TasksFragBinding has been created successfully. But where can I find the declaration for TasksFragBinding? And why is it generated?
