### ISSUE TITLE
Does event wrapper pattern replace the use of SingleLiveEvent?

### ISSUE THREAD

**Issue by carterchen247** [googlesamples/android-architecture#593]
According to this medium [article](https://medium.com/androiddevelopers/livedata-with-snackbar-navigation-and-other-events-the-singleliveevent-case-ac2622673150), it pointed out that SingleLiveEvent would be an "OK" option, and using a event wrapper pattern would be a "recommended" approach. As I review the code of [Google I/O project](https://github.com/google/iosched) this year, I could not find any code which is implemented by SingleLiveEvent. So I'm wondering the existing scenarios which adopt SingleLiveEvent can be replaced by the event wrapper pattern or not.

**Comment by JoseAlcerreca** [comment]
Yep we're doing that in #629 #630
