### ISSUE TITLE
New sample: mvp-fragmentless

### ISSUE THREAD

**Issue by JoseAlcerreca** [googlesamples/android-architecture#6]
Sample based on MVP but without fragments.

**Comment by atarsdnh** [comment]
Is this an open issue for anyone to jump on? 

I already implemented a sample. https://github.com/atarsdnh/MVPExample

Does it work for this issue? Would love to help.

**Comment by Rainer-Lang** [comment]
Is it possible to write the readme in English?

**Comment by malmstein** [comment]
it is @atarsdnh, don't forget reading the contributing guidelines [here](https://github.com/googlesamples/android-architecture/blob/master/CONTRIBUTING.md) before submitting a PR

**Comment by atarsdnh** [comment]
@Rainer-Lang Sure, I will write it.

@malmstein OK. I will read it.

**Comment by Syhids** [comment]
I made a sample without fragments using todo-mvp as a base branch https://github.com/Syhids/android-architecture/tree/todo-mvp-fragmentless

I thought a lot about defining the 'active' state of the views, and the current implementation is the best I could make to keep the examples comparable, but I would love to hear your ideas :)

**Comment by JoseAlcerreca** [comment]
@Syhids it looks great. I'd like to add it to the list in the main README, as an un-official sample. Could you change the README as well to avoid confusing people?

**Comment by JoseAlcerreca** [comment]
Added to the main README. Thanks @Syhids!
