### ISSUE TITLE
Build sync fail - Why? and how to solve?

### ISSUE THREAD

**Issue by DharitParmar** [googlesamples/android-architecture#606]
Failed to resolve: recyclerview-v7
Open File

Failed to resolve: espresso-idling-resource
Open File

Failed to resolve: espresso-contrib
Open File

Failed to resolve: espresso-core
Open File

**Comment by dino9** [comment]
@DharitParmar I was running on the same issue. In the below implementation, just swap the position of repository. 
```
repositories {
        jcenter()
        google()
    }
```

```
allprojects {
    repositories {
        jcenter()
        google()
    }
}
```

**Comment by pramodit** [comment]
Worked when i put google() in first place and then jcenter(). @dino9

**Comment by DharitParmar** [comment]
@dino9 @pramodit Same here worked with google() first and then jcenter().

Why is it so? What is the reason?

**Comment by ShirleyLuoppx** [comment]
are you Chinese or English?Cause i think ther're Chinese who use the github,so problem is coming ,why do you use English to discuss with others otherwise we're Chinese

**Comment by JoseAlcerreca** [comment]
Fixed in mvp branches
