### ISSUE TITLE
how to run unittest and uitest ?

### ISSUE THREAD

**Issue by yipinghuo** [googlesamples/android-architecture#63]
I download the android-architecture-todo-mvp-loaders program，and then i run TaskScreenTest.java,but i got wrong ,the follow is the message.i don't know how to do ?i want do unit test and ui test for a program ?Thank you very much!
![d](https://cloud.githubusercontent.com/assets/5533880/14976532/14a26c9a-113f-11e6-8dc7-96189abfcbaa.JPG)

**Comment by JoseAlcerreca** [comment]
Did you unlock the device and disabled animations?

There are more instructions here, for UI and Unit tests from AS or command line.
https://github.com/googlesamples/android-testing-templates/tree/master/AndroidTestingBlueprint
