### ISSUE TITLE
[todo-mvvm-live] What is "Live" about the `todo-*-live` versions? They are not using LiveData integration of Room DAO.

### ISSUE THREAD

**Issue by Zhuinden** [googlesamples/android-architecture#639]
I was trying to find a sample that uses `LiveData<List<T>>` from Room DAO, to show how to use reactive Room DAO which is pretty much the most important feature of Room, but apparently not even the LiveData samples use Room DAO's `LiveData` integration.

What makes the `Live` branches special, then?

**Comment by Zhuinden** [comment]
Thankfully https://github.com/googlesamples/android-architecture-components/blob/1c2af45fa614867a1a40047e2bd4f9b3fe61778e/BasicSample/app/src/main/java/com/example/android/persistence/db/dao/ProductDao.java#L30-L31 will suffice.

**Comment by JoseAlcerreca** [comment]
They use LiveData and ViewModels (so the lifecycle package).

The official basic sample for Room seems to be using LiveData
https://github.com/googlesamples/android-architecture-components/blob/master/BasicSample/app/src/main/java/com/example/android/persistence/db/dao/CommentDao.java
