### ISSUE TITLE
[todo-mvp-clean, todo-mvp-kotlin] - How best to accommodate users through the cloud?

### ISSUE THREAD

**Issue by BARJ** [googlesamples/android-architecture#647]
I'm trying to add user management to the ToDo App where the user's tasks are stored on the cloud and can be accessed by that user on various devices.

If I would like to incorporate user login and management into the ToDo App, would I add the logic to the existing TaskRepository and the underlying local and remote data sources or would it be better to include a separate UserRepository?

**Comment by JoseAlcerreca** [comment]
Note that if you use an Auth provider, like Firebase Auth, you won't need a repository because it's handled for you.

But yes, each distinct collection of items can have its own repository.
