### ISSUE TITLE
Wanted: Small two-way databinding example with text fields updating each other

### ISSUE THREAD

**Issue by peon73** [googlesamples/android-architecture#648]
Can Google please make a more minimalistic app focused at illustrating the two-way databinding, i.e. an app with less noise than the app "todo-mvvm-databinding" which has about 36 Java classes and 10 layout files?
(I think a small example should not have to be more than one layout file and three Java classes)
I have tried to implement such a small currency converter app (with the only purpose to try figure out how to do it properly) only using three Java classes.
https://github.com/peon73/CurrencyConverter

My above small app works, but I do not believe I have done it in the best way.

In particular, I would like to see the best solution for how to do these things:
* How to (in the best way) avoid text field modifications triggering updates in an eternal loop, when you are developing an app with text fields updating each other (e.g. a currency converter)?
* Should you really expose "MutableLiveData" or how can you avoid it to implement better encapsulation?
* Is it necessary to add observers from the activity or how can you implement setters in the view model which becomes invoked (i.e. the "two"-way binding) while at the same time using LiveData being pulled from the layout file (i.e. the other direction of the binding)?
* How to use the most up to date code, e.g. "androidx" instead of "android.support" libraries, and also "LiveData" instead of "ObservableField" (since, as far as I understand, the "ObservableField" code currently used in "todo-mvvm-databinding" is "oldish"/deprecated kind of code and these days should be replaced with "LiveData" instead?)

**Comment by JoseAlcerreca** [comment]
Have you checked out the official 2-way sample?

**Comment by BlaydonLogics** [comment]
Have you tried ADB shellkit. If not give it a try, I use it occasionally to experiment.
