### ISSUE TITLE
Runtime warning

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-architecture#653]
Hello,
when I run your samples on the emulator, I get this runtime warning:
> W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.example.android.architecture.blueprints

As a result, the screen is blank.

**Comment by IgorGanapolsky** [comment]
I believe the issue was that I imported just **smoothie-sample** instead of the entire git repo.  Can you please confirm what is the best way to run your samples?

**Comment by JoseAlcerreca** [comment]
What branch?

**Comment by IgorGanapolsky** [comment]
I believe it works now.  I tried **todo-mvp-kotlin**
