### ISSUE TITLE
Kotlin version of 'todo-mvp-dagger'

### ISSUE THREAD

**Issue by MonikaJethani** [googlesamples/android-architecture#656]
@JoseAlcerreca Can I work on Kotlin version of 'todo-mvp-dagger'?

**Comment by JoseAlcerreca** [comment]
It'd be more interesting to move todo-mvvm-live-kotlin to dagger actually....

But we're close to pulling the code from the testing codelab and starting again so I'd wait a couple of weeks.

**Comment by MonikaJethani** [comment]
Ok @JoseAlcerreca , Please let me know if any help is required.
