### ISSUE TITLE
New sample: mvp-dagger

### ISSUE THREAD

**Issue by JoseAlcerreca** [googlesamples/android-architecture#7]
Based on MVP but using Dagger2 for dependency injection.

**Comment by paddyzab** [comment]
Hey @JoseAlcerreca would love to take care of this during weekend.
Are you working on it? Do not want to duplicate effort.

Cheers.

**Comment by JoseAlcerreca** [comment]
It was forked a while ago from todo-mvp so it probably needs a `git merge todo-mvp` and a big conflict resolution.

Take a look at 

https://github.com/googlesamples/android-architecture/tree/dev-todo-mvp-dagger/todoapp

I'd use `git difftool -d origin/dev-todo-mvp-dagger -- .` first, if you have a nice difftool installed like meld it will show differences. They should be as small and few as possible.

and feel free to open a PR against that branch. 

The prod/mock flavors and the Injection class have to be removed from it.

**Comment by JoseAlcerreca** [comment]
Also, before committing code please highlight the changes you plan to make. Thanks!

**Comment by Ericliu001** [comment]
I've built an sample weather app using MVP and Dagger2, but not sure the mvp is structured the same way as you are planning to.
Here is the link https://github.com/Ericliu001/Weather2016
