### ISSUE TITLE
On todo-databinding, remove logic from layout files

### ISSUE THREAD

**Issue by hypest** [googlesamples/android-architecture#72]
Hey guys, thanks for the awesome repo and the samples!

Not sure if this is nitpicking or not but, even though the `databinding` lib offers quite an elaborate set of options to add logic directly into the layout files (example: [determining the visibility of an element in `statistics_frag.xml`](https://github.com/googlesamples/android-architecture/blob/todo-databinding/todoapp/app/src/main/res/layout/statistics_frag.xml#L41)) I think that _power_ should be relinquished to the Presenter since one is in place.

In essence, since the `todo-databinding` arch is based on MVP, it's probably more suitable to remove any logic from all layout files and put it in appropriate getters in the respective presenters (or ViewModels as depicted in [README.md](https://github.com/googlesamples/android-architecture/blob/todo-databinding/README.md)). Databinding will still be used in the layouts but only to _connect_ to the presenter.

I could work on that goal if this gets a few 👍
Thanks! 😃 ❤️

**Comment by JoseAlcerreca** [comment]
Hey hypest,

As we wrote in the README

> It's doesn't follow a strict Model-View-ViewModel or a Model-View-Presenter pattern, as it uses both View Models and Presenters.

That's why it's not called `todo-mvp-databinding`.

In this case I think the responsibilities are very well defined: the presenter loads the data, the viewmodel adapts it and the layout renders it, using very small chunks of logic. This is the idiomatic way. 

We could explore a pure `todo-mvp-databinding` sample, though. You could start using this option: https://github.com/googlesamples/android-architecture/wiki/Unofficial-samples

Thanks!

**Comment by hypest** [comment]
Thanks for the feedback @JoseAlcerreca !

Only to make probably more clear what I mean, I'm not raising this issue to highlight the existence of both ViewModel and Presenter, on the contrary, it's an opportunity to use them (well, `ViewModels` more specifically in this sample) as the harbour of _business logic_ instead of the layout itself. Main argument for it would be the typical one about testability (without relying on the real `View`s to be present and touchable) and the even more clear separation of concern between the layout files and the code files.

I see your point about a `todo-mvp-databinding` sample though and I've also seen that there is an open ticket for an MVVM one (https://github.com/googlesamples/android-architecture/issues/59). I'd prolly wait for that one to hash out first as that would probably cover this issue here as well.

Again, thanks for clearing it up and offering more insight! 😃

**Comment by JoseAlcerreca** [comment]
Cool thanks, closing this one!
