### ISSUE TITLE
on todo-mvp, move logic from view to presenter

### ISSUE THREAD

**Issue by ISatya** [googlesamples/android-architecture#85]
In AddEditTaskFragment, the logic to decide whether to update task or create a new task is made and presenter method is called accordingly.

```
fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (isNewTask()) {
                    mPresenter.createTask(
                            mTitle.getText().toString(),
                            mDescription.getText().toString());
                } else {
                    mPresenter.updateTask(
                            mTitle.getText().toString(),
                            mDescription.getText().toString());
                }
            }
        });
```

Shouldn't the view just pass the user action to presenter and let presenter decide?
As the presenter knows whether its a new task or a task update, this decision can be deferred to presenter and view does not have to store any information related to the task.
Thoughts?

**Comment by JoseAlcerreca** [comment]
Yep we talked about that, that would be the way to go. The presenter already has the nullable task ID, so there's no reason to pass it to the view with ARGUMENT_EDIT_TASK_ID. 

Easy PR, any takers?

**Comment by tomaszrykala** [comment]
@JoseAlcerreca I've updated open https://github.com/googlesamples/android-architecture/pull/81 with this change.
