### ISSUE TITLE
Request - Un-official sample

### ISSUE THREAD

**Issue by kdani41** [googlesamples/android-architecture#87]
I wanna submit an un official sample request. 
[Sample500px](https://github.com/kdani41/Sample500px) 
I have made this sample combining dagger2, rxjava, and retrofit2 
Please let me know your thoughts :)
Thanks to the community for making this project open source 👍

**Comment by JoseAlcerreca** [comment]
Hi, projects need to follow the app spec, I don't think that one does. Thanks!

**Comment by kdani41** [comment]
@JoseAlcerreca  Can you please elaborate what's in the app spec?

**Comment by JoseAlcerreca** [comment]
https://github.com/googlesamples/android-architecture/wiki/To-do-app-specification

**Comment by kdani41** [comment]
Thanks @JoseAlcerreca . 
Just a question is anyone already working on combining these 3 main libraries dagger2, rxjava, and retrofit2? If not then I can start a project and create an unofficial sample with app spec

**Comment by insomniatt** [comment]
@kdani41 you are a good man, i like this project Sample500px , it is really a good sample to learn new techs now.
