### ISSUE TITLE
New sample: MVP-RxJava

### ISSUE THREAD

**Issue by JoseAlcerreca** [googlesamples/android-architecture#9]
Based on MVP but using RxJava for asynchronous jobs, event handling and data observation.

**Comment by Rainer-Lang** [comment]
This would be great. I hope with usage of Dagger2.

**Comment by clarle** [comment]
@ErikHellman Are you already working on this? Or is this an open issue for anyone to jump on? Would love to help.

**Comment by JoseAlcerreca** [comment]
@Rainer-Lang RxJava with Dagger2 would come after this one and the Dagger2 sample.

@clarle He is! But there will be more RxJava samples :)

**Comment by ThinWonton** [comment]
expect and concern about it.

**Comment by Rainer-Lang** [comment]
@ErikHellman You are implementing this sample, right? What is your suggestion for eg long running tasks like network requests and screen rotation (no abortion of the network request)? Will you integrate this in the example?

**Comment by Calamus-Cajan** [comment]
The samples were done?

**Comment by Rainer-Lang** [comment]
What would you like to do? 
If you want, just make a PR. :-)

**Comment by andrewpiggy** [comment]
When will MVP-RxJava be launched?

**Comment by geniushkg** [comment]
Hey folks ,

1) is MVP -RxJava done , any help needed I will be more than happy to do so.
2) anything on MVP -  RxJava + Realm possible ?
suggestions welcomed , I am planning to build one.

**Comment by JoseAlcerreca** [comment]
@ErikHellman @florina-muntenescu can you give an update on this sample? All tests pass now, looking good!

**Comment by florina-muntenescu** [comment]
The sample (here)[https://github.com/googlesamples/android-architecture/tree/dev-todo-mvp-rxjava] is an implementation that uses RxJava as a way of communicating between the data model layer and the presenter. The ``TasksLocalDataSource`` uses SqlBrite, to query the database and get the results as streams. 
We kept the same way of injecting dependencies as in the main todo-mvp project, to keep it as simple as possible. 
The Presenter contracts and the Views are unchanged. 
From me and @ErikHellman this sample is done.

**Comment by JoseAlcerreca** [comment]
Sample promoted to stable!
https://github.com/googlesamples/android-architecture/tree/todo-mvp-rxjava

Thanks @ErikHellman, @florina-muntenescu and everyone involved!
