### ISSUE TITLE
Some advice

### ISSUE THREAD

**Issue by duo2005duo** [googlesamples/android-architecture#97]
I think presenter should not control view.The view should control itself instead in MVP architecture.The presenter is for changing the model bean to view bean and some other additional job . 
if the presenter controls view , there will be something like 'View->Presenter->View->Presenter->View',which I think it's wrong.The presenter will have to  changes if the view interface change!

**Comment by initialjie** [comment]
Yes, it may be an issue for what you say "View->Presenter->View->Presenter->View".
You may consider a straight work flow coding pattern like "Flux" which is proposed by Facebook.

**Comment by duo2005duo** [comment]
@initialjie  Thanks for mentioning "Flux".It seems great!

**Comment by duo2005duo** [comment]
@initialjie I think the 'Flux' is just a kind of MVP but there are a few changes below:
1. The view is not only a view but also a controller,the problem of "View->Presenter->View->Presenter->View" will never happen;(which I think it is essential)
2. The "Flux" decouples VP with 'Stores',which makes P never depend on V . We will not have to make interfaces of both V and P because there are only one-way dependents .
The 'Flux' is great for the loose coupling between V and P.

**Comment by initialjie** [comment]
@duo2005duo 
Yes, and I think Flux's purpose is to decouple dependence by following a straight work flow programming  pattern.
But I don't consider it as a variant of MVP because V and P do not recognize each other either in Flux.
I think Flux is a new programming pattern :)

**Comment by duo2005duo** [comment]
It's of no great importance whether the flux is a variant of MVP.
But they are similar: 
The ControllView depends on ActionCreator.The ActionCreator just do the same thing as Presenter does,retrieving data from Model asynchronously.In other word,V recognize P.So I think it may be wrong V and P do not recognize each other as you said.
另外，我觉得用英文很费力。

**Comment by JoseAlcerreca** [comment]
Thanks! Closing as this is not an issue.
