### ISSUE TITLE
What should I do if TasksDataSource changes? 

### ISSUE THREAD

**Issue by 81813780** [googlesamples/android-architecture#98]
- As I said , if I want to add method or change method in TasksDataSource , I have to modify the other three implementation classes at the same time. 

- Imagine if I just want to add method `loadMoreTasksByPage(int page)` get remote data,should I add it to TasksDataSource ? If so , I have to implements it in TasksLocalDataSource . 

- In real project , I think there will be more changes in DataSource . I'm very interested in MVP+Repository pattern , but there is still some confusion about the use of the Repository .

**Comment by Juude** [comment]
In my opinion, in real wold cases. 
TasksRemoteDataSource and TasksLocalDataSource should not implement TasksDataSource, they should provide much low level data access methods. we can also use dynamic proxy(just in the case of Retrofit) or apt to generate code dynamically from the interface.

**Comment by 81813780** [comment]
First of all , thanks for your reply . I agree with your opinion . then , as I understand , the reason why they both implement TasksDataSource was that it be simple to mock test . in this case , just like  `mock/data/FakeTasksRemoteDataSource.java`

**Comment by JoseAlcerreca** [comment]
Yes, it would make sense to split DataSource and Repository in two if you need to.
