### ISSUE TITLE
Small paradox between samples and android studio template

### ISSUE THREAD

**Issue by AlirezaAkbarix** [googlesamples/android-architecture#99]
First of all thanks for your perfect sample.
Second I should mention a paradox between naming layouts in Android studio template that chooses `activity_main.xml` for `MainActivity.java` and in samples you named like `main_act.xml`. It's not such an important issue but as a master in teaching android that explains the rule of naming files, it can make confuse my students and other newbies in android.

**Comment by JoseAlcerreca** [comment]
Thanks for your issue, I have to agree that it's not an important one :) I don't think there are hard and fast rules for that.
